import type { UiDictionary } from "../schemas";

export const ui = {
  metadata: {
    defaultTitle: "AI Orchestrator Guide",
    titleTemplate: "%s | AI Orchestrator Guide",
    description:
      "A practice-oriented learning site for developer-orchestrators training AI workflow orchestration, source-of-truth decisions, quality gates, and agentic loop judgment.",
    siteName: "AI Orchestrator Guide",
  },
  layout: {
    brandTitle: "Orchestrator Learning",
    brandSubtitle: "Practice-oriented workflow judgment",
    chapterNavigation: "Chapter navigation",
    mobileQuickNavigation: "Mobile quick navigation",
    overview: "Overview",
    languageLabel: "Language",
    switchLanguage: "Switch language",
    closeChapterPicker: "Close chapter picker",
    closeChapters: "Close chapters",
  },
  navigation: {
    chapters: "Chapters",
    continue: "Continue",
    practice: "Practice",
    refs: "Refs",
    previous: "Previous",
    next: "Next",
    current: "Current",
    planned: "Planned",
    chapterMap: "Chapter map",
    practiceScenarios: "Practice scenarios",
  },
  home: {
    mobileContext: "Overview",
    eyebrow: "Practice-oriented learning product",
    title: "AI workflow orchestration for developer judgment",
    summary:
      "Learn to choose authority layers, workflow levels, audit depth, quality gates, and the next orchestrator action for AI coding tasks.",
    progressLabel: "Current chapter progress",
    chapterPath: (count) => `${count} chapter path`,
    startPrompt: "Start with the first available chapter",
    howToEyebrow: "How to use it",
    howToTitle: "Start focused, then expand",
    howToBody:
      "This overview keeps the learning path compact. Open a chapter route to read, make the checkpoint decision, and try the lightweight practice tool attached to that chapter.",
    startLearning: "Start learning",
    practice: "Practice",
    references: "References",
    mapEyebrow: "MVP path",
    mapTitle: "Chapter map",
    mapBody:
      "Each item opens a chapter route with learning content, a decision checkpoint, and practice focused on one orchestrator skill.",
  },
  chapter: {
    mobileContext: (order) => `Chapter ${order}`,
    progressLabel: "Current chapter progress",
    progressText: (order, total) => `Chapter ${order} / ${total}`,
    practiceTargetEyebrow: "Practice target",
    practiceTargetTitle: "What this chapter trains",
    patternSetEyebrow: "Pattern set",
    patternSetTitle: "Six workflow patterns",
    gateSetEyebrow: "Gate set",
    gateSetTitle: "Seven quality gates",
    useWhen: "Use when",
    avoidWhen: "Avoid when",
    risk: "Risk",
    example: "Example",
    watchOut: "Watch out",
    sourceNotesEyebrow: "Source notes",
    sourceNotesTitle: "Research anchors for this slice",
    sourceNotesBody:
      "These are lightweight anchors for later source-backed validation. They are attached to external factual claims, not product decisions.",
    adjacentLabel: "Adjacent chapters",
  },
  practice: {
    mobileContext: "Practice",
    eyebrow: "Practice scenarios",
    title: "Practice scenarios",
    summary:
      "Use the eight MVP scenarios to practice mixed orchestrator judgment across authority, workflow level, audit depth, gates, and durable correction.",
    progressLabel: "Route status",
    scenarioCount: "8 scenarios",
    capstone: "Cumulative capstone",
    howToEyebrow: "How to use it",
    howToTitle: "Complete decisions before review",
    howToBody:
      "This is the assessment workspace. Six scenarios test a compact mixed decision; two full capstones require authority, workflow, gates, next action, durable correction, and a self-reviewed rationale before final feedback.",
  },
  references: {
    mobileContext: "References",
    eyebrow: "References / advanced reading",
    title: "References and advanced reading",
    summary:
      "Verified source anchors, maintenance metadata, and optional advanced reading for external claims about agents, workflows, tools, HITL, evals, and permissions.",
    progressLabel: "Route status",
    backlog: "Source lifecycle",
    validateLater: "Verified 2026-07-11",
    sourcePolicyEyebrow: "Source policy",
    sourcePolicyTitle: "Use sources for external claims",
    sourcePolicyBody:
      "Product decisions come from the calibration artifact. External factual claims use exact primary sources. Vendor behavior remains scoped to the named product and must be refreshed against current official docs.",
    operationalEyebrow: "Operational index",
    operationalTitle: "Find the control you need",
    operationalBody:
      "Use these links during a live task. They point to canonical chapter content instead of duplicating the framework here.",
    actionsTitle: "Actions / stop decisions",
    actionsBody:
      "Decide whether the agent should continue, stop, ask for help, or zoom out.",
    loopDecisionsLink: "Agentic loop decisions",
    zoomOutLink: "Zoom-out signals",
    gatesTitle: "Quality gates",
    gatesBody: "Jump directly to the gate that matches the current risk.",
    patternsTitle: "Workflow patterns",
    patternsBody: "Open the canonical pattern entry for the task shape you are classifying.",
    checklistTitle: "Operating checklist",
    checklistBody: "Run the before / during / after checklist for an active coding-agent task.",
    checklistLink: "Open the operating checklist",
    practiceTitle: "Practice modes",
    practiceBody:
      "Chapter 12 is the guided learning bridge. The Practice route is the direct scenario workspace.",
    guidedPracticeLink: "Guided practice chapter",
    directPracticeLink: "Direct practice workspace",
    sourceLifecycle: {
      scopeLabel: "Scope",
      verifiedLabel: "Verified",
      volatilityLabel: "Volatility",
      vendorScopeLabel: "Source scope",
      volatilityLabels: {
        stable: "Stable concept",
        "vendor-specific": "Vendor-specific",
        heuristic: "Heuristic",
      },
    },
    groups: [
      {
        category: "core",
        eyebrow: "Core references",
        title: "Workflow and agent concepts",
        description:
          "Primary anchors for workflow patterns, agent loops, HITL, and evals.",
      },
      {
        category: "vendor-docs",
        eyebrow: "Vendor docs",
        title: "Current product behavior",
        description:
          "Exact official docs for scoped product behavior. Refresh these claims as vendor behavior changes.",
      },
      {
        category: "advanced",
        eyebrow: "Advanced reading",
        title: "Next-layer concepts",
        description:
          "Keep these as optional reading. They should not become the MVP blueprint.",
      },
    ],
  },
  learning: {
    decisionCheckpoint: "Decision checkpoint",
    checkpointTitle: "Make the authority call",
    hideExpectedMove: "Hide expected move",
    revealExpectedMove: "Reveal expected move",
    durableHabit: "Durable habit:",
    relatedConcepts: "Related concepts",
    sourceAnchors: "Source anchors",
    sourceListLabel: "Source anchors for this chapter",
  },
  interactives: {
    eyebrow: "Interactive",
    scenariosLabel: "scenarios",
    choiceInstruction: "Choose the orchestrator move for this scenario.",
    correctMove: "Correct move:",
    consequence: "Consequence:",
    relatedGates: "Related gates",
    chooseHint: "Choose a move to reveal feedback.",
    selfCheckTitle: "Self-check / reveal cards",
    selfCheckIntro:
      "Use these quick checks to distinguish plausible answers, evidence, and durable workflow improvement.",
    authorityMatrixTitle: "Source-of-Truth Authority Matrix",
    authorityMatrixIntro:
      "Choose the authority layer before choosing whether the agent can continue.",
    authorityLayer: "Authority layer",
    sourceOfTruth: "Source of truth",
    workflowClassifierTitle: "Workflow Classifier",
    workflowClassifierIntro:
      "Classify the workflow pattern and notice the orchestrator risk before work starts.",
    targetPattern: "Target pattern",
    risk: "Risk",
    agenticLoopTitle: "Agentic Loop Simulator",
    agenticLoopIntro:
      "Practice deciding whether the loop should continue, stop, zoom out, or ask for human input.",
    localLearningTitle: "Local Learning Loop Wizard",
    localLearningIntro:
      "Classify the failure signal and route the correction to the smallest durable layer that will intercept it later.",
    failureSignal: "Failure signal",
    durableTarget: "Durable target",
    permissionRiskTitle: "Permission / Risk Gate Stress-Test",
    permissionRiskIntro:
      "Pause, explain the risk, identify the gate, and decide whether to ask approval, validate, stop, or zoom out.",
    practiceScenariosTitle: "Practice Scenarios",
    practiceScenariosIntro:
      "Mixed scenarios combine ownership, source of truth, UI QA, zoom-out, durable correction, permission gates, and high-risk boundaries.",
    durableCorrectionCandidate: "Durable correction candidate",
    guidedMode: "Guided practice",
    guidedModeIntro:
      "Use immediate feedback to learn how a mixed situation decomposes into authority, evidence, gates, action, and durable correction.",
    assessmentMode: "Assessment workspace",
    assessmentModeIntro:
      "Complete the structured decisions before reviewing the calibrated response. Full capstones keep all correctness feedback until final submit.",
    evidence: "Available evidence",
    beginAssessment: "Begin assessment",
    step: "Step",
    of: "of",
    back: "Back",
    nextStep: "Next step",
    submitDecision: "Submit decision",
    submitAssessment: "Submit full assessment",
    checkDecision: "Check decision",
    continueAfterReview: "Continue after review",
    viewGuidedSummary: "View guided summary",
    reset: "Reset",
    retry: "Retry scenario",
    requiredChoice: "Choose one option before continuing.",
    requiredGates: "Select at least one quality gate before continuing.",
    requiredRationale: "Add a short rationale before submitting.",
    reviewTitle: "Dimension-by-dimension review",
    reviewIntro:
      "Structured decisions are checked deterministically. The written rationale is self-reviewed, not machine-graded.",
    guidedReviewIntro:
      "Review the complete decision sequence you practiced, then use the transfer question to retrieve the framework in a new context.",
    decisionTrace: "Decision trace",
    traceLabels: {
      "authority-source": "Authority / source",
      "workflow-audit": "Workflow / audit",
      gates: "Quality gates",
      "next-action": "Next action",
      "durable-correction": "Durable correction",
      rationale: "Rationale self-review",
    },
    detailedReview: "Detailed review",
    transferQuestion: "Transfer question",
    memoryCue: "Memory cue",
    evidenceWouldChange: "Evidence that would change this decision",
    selfReviewed: "Self-reviewed",
    selectedAnswer: "Your decision",
    calibratedRationale: "Calibrated rationale",
    rationaleSelfReview: "Rationale self-review",
    rationaleNotGraded:
      "No score is assigned to your wording. Compare it with the rubric and calibrated rationale.",
    missingCriticalGates: "Missing critical gates",
    gateSelected: "Selected",
    gateNotSelected: "Not selected",
    reviewStates: {
      aligned: "Aligned",
      "conditionally-reasonable": "Conditionally reasonable",
      "needs-review": "Needs review",
    },
    gateClassifications: {
      required: "Required",
      useful: "Useful when conditions apply",
      unnecessary: "Unnecessary for this evidence",
      insufficient: "Insufficient on its own",
    },
    loopStage: "Decision stage",
    loopFeedback: "Decision feedback",
    loopContinue: "Continue to new evidence",
    loopOutcome: "Loop outcome",
    loopOutcomes: {
      complete: "Complete with evidence",
      stopped: "Stopped",
      "zoomed-out": "Zoomed out",
      escalated: "Escalated to a human",
    },
  },
} satisfies UiDictionary;
