import type {
  AgenticLoopCase,
  AuthorityMatrixCase,
  DecisionScenario,
  LocalLearningCase,
  PracticeScenario,
  SelfCheckCard,
  WorkflowClassifierCase,
} from "../schemas";

export const selfCheckCards = [
  {
    id: "plausible-vs-repo-truth",
    prompt:
      "Agent пояснює architecture через знайому framework convention, але ще не перевірив цей repo.",
    revealTitle: "Що має пам'ятати orchestrator?",
    reveal:
      "Це plausible continuation, а не project truth. Спершу оберіть authority layer, потім перевірте факти repo або docs перед дією agent.",
    relatedGates: ["source-of-truth", "ownership"],
  },
  {
    id: "session-vs-durable",
    prompt:
      "Після помилки agent каже, що наступного разу перевірить поведінку UI, але rule, test, doc або gate не змінюються.",
    revealTitle: "Це durable?",
    reveal:
      "Ні. Це session-local correction. Durable improvement потребує збереженого rule, skill, test, docs update, validation-перевірки, quality gate або stop condition.",
    relatedGates: ["durable-correction"],
  },
  {
    id: "validation-vs-acceptance",
    prompt: "Build проходить після зміни UI, але фактичний screen ніхто не перевірив.",
    revealTitle: "Чи можна закрити задачу?",
    reveal:
      "Ще ні. Passing validation є доказом, але видима поведінка потребує UI QA gate перед lifecycle close.",
    relatedGates: ["validation", "ui-qa", "lifecycle-close"],
  },
] satisfies SelfCheckCard[];

export const authorityMatrixCases = [
  {
    id: "memory-vs-docs",
    title: "Конфлікт docs і Memory",
    situation:
      "Memory каже, що project uses one API client, але repo docs та imports показують інший.",
    authorityLayer: "Repo facts і project docs",
    sourceOfTruth: "Поточні docs, imports і call sites у repository",
    choices: [
      {
        id: "ask-model",
        label: "Спитати модель, яке джерело ймовірно новіше",
        feedback: "Це додає ще одне припущення. Orchestrator потрібні докази source-of-truth.",
      },
      {
        id: "inspect-repo",
        label: "Перевірити docs та imports, потім заземлити відповідь у них",
        feedback: "Правильно. Розв'яжіть конфлікт через перевірку durable repo layer.",
        correct: true,
      },
      {
        id: "trust-memory",
        label: "Довіритися Memory, бо її збережено раніше",
        feedback: "Memory може бути корисним контекстом, але актуальні факти repo мають перевагу під час конфлікту.",
      },
    ],
    correctMove: "Використайте repo docs і актуальні imports як authority layer, потім продовжуйте лише після розв'язання конфлікту.",
    consequence: "Agent не будує рішення на застарілих або вигаданих project conventions.",
    relatedGates: ["source-of-truth", "validation"],
  },
  {
    id: "tool-docs",
    title: "Твердження про поведінку інструмента",
    situation:
      "Agent стверджує, що coding-agent product завжди asks approval перед редагуванням project instruction files.",
    authorityLayer: "Поточні official product docs",
    sourceOfTruth: "Поточні official docs для конкретного інструмента і version",
    choices: [
      {
        id: "generalize",
        label: "Трактувати це як універсальне coding-agent rule",
        feedback: "Поведінка продукту змінюється і відрізняється між інструментами. Не узагальнюйте.",
      },
      {
        id: "current-docs",
        label: "Перевірити актуальні official docs перед таким твердженням",
        feedback: "Правильно. Поведінка конкретного інструмента потребує актуальної official documentation.",
        correct: true,
      },
      {
        id: "skip",
        label: "Пропустити твердження і спиратися лише на локальну preference",
        feedback: "Можна уникнути продуктового твердження, але якщо ви його робите, потрібні актуальні docs.",
      },
    ],
    correctMove: "Або уникайте твердження про конкретний продукт, або перевірте його за актуальними official docs.",
    consequence: "Сайт не вводить learners в оману щодо поведінки vendor.",
    relatedGates: ["source-of-truth", "permission"],
  },
] satisfies AuthorityMatrixCase[];

export const workflowClassifierCases = [
  {
    id: "known-sequence",
    title: "Відома repo edit sequence",
    situation: "Невелика copy fix потребує огляду, редагування, lint і підсумку. Шлях відомий.",
    patternId: "prompt-chaining",
    choices: [
      {
        id: "agent",
        label: "Agent",
        feedback: "Повний agent loop дає більше autonomy, ніж потрібно цій задачі.",
      },
      {
        id: "prompt-chaining",
        label: "Prompt chaining",
        feedback: "Правильно. Короткої визначеної послідовності достатньо.",
        correct: true,
      },
      {
        id: "parallelization",
        label: "Parallelization",
        feedback: "Parallel workers додають накладні витрати для такого малого відомого шляху.",
      },
    ],
    correctMove: "Використайте prompt chaining із легкою validation gate.",
    consequence: "Задача лишається малою і уникає зайвих agentic накладних витрат.",
    relatedGates: ["validation"],
  },
  {
    id: "high-risk-route",
    title: "Зміна auth boundary",
    situation: "Agent хоче змінити auth/API boundary, хоча ownership досі нечіткий.",
    patternId: "routing",
    choices: [
      {
        id: "routing",
        label: "Routing",
        feedback: "Правильно. Спрямуйте це в high-risk lane перед будь-яким редагуванням.",
        correct: true,
      },
      {
        id: "evaluator",
        label: "Evaluator-optimizer",
        feedback: "Оцінювання важливе пізніше, але спершу треба класифікувати risk lane.",
      },
      {
        id: "prompt-chain",
        label: "Prompt chaining",
        feedback: "Простий chain може сховати крок класифікації ризику.",
      },
    ],
    correctMove: "Спрямуйте задачу в high-risk workflow із source-of-truth, ownership, permission і validation gates.",
    consequence: "Workflow зупиняє ризикові boundary changes до випадкового scope creep.",
    relatedGates: ["permission", "ownership", "source-of-truth", "validation"],
  },
  {
    id: "independent-repo-inspection",
    title: "Незалежна перевірка repo",
    situation:
      "Для оцінки міграції потрібні окремі переліки API callers, UI consumers і test coverage. Ці читання не залежать одне від одного.",
    patternId: "parallelization",
    choices: [
      {
        id: "orchestrator-worker",
        label: "Orchestrator-worker",
        feedback: "Orchestrator може синтезувати результати пізніше, але зараз задача складається з незалежних read-only перевірок.",
      },
      {
        id: "parallelization",
        label: "Parallelization",
        feedback: "Правильно. Незалежний збір evidence можна виконати паралельно, а потім синтезувати результати.",
        correct: true,
      },
      {
        id: "evaluator-optimizer",
        label: "Evaluator-optimizer",
        feedback: "Поки що немає candidate output, який потрібно ітеративно оцінювати.",
      },
    ],
    correctMove: "Паралельно зберіть незалежні переліки, а потім узгодьте findings перед плануванням змін.",
    consequence: "Evidence надходить швидше без write conflicts або прихованих залежностей.",
    relatedGates: ["source-of-truth", "ownership"],
  },
  {
    id: "coordinated-module-migration",
    title: "Координована міграція модулів",
    situation:
      "Міграція shared API охоплює чотири модулі з окремими owners. Кожен модуль можна адаптувати окремо, але один план має контролювати contracts та інтеграцію.",
    patternId: "orchestrator-worker",
    choices: [
      {
        id: "parallelization",
        label: "Parallelization",
        feedback: "Паралельна робота сама по собі не забезпечує ownership contract, синтез результатів та контроль інтеграції.",
      },
      {
        id: "orchestrator-worker",
        label: "Orchestrator-worker",
        feedback: "Правильно. Orchestrator може декомпозувати роботу за ownership і звірити evidence workers з одним contract.",
        correct: true,
      },
      {
        id: "agent",
        label: "Agent",
        feedback: "Open-ended autonomy зайва, коли декомпозиція та ownership boundaries уже відомі.",
      },
    ],
    correctMove: "Orchestrator визначає contract, призначає bounded work для модулів і перевіряє інтегрований результат.",
    consequence: "Workers лишаються в ownership boundaries, а інтеграція залишається контрольованою.",
    relatedGates: ["ownership", "validation", "lifecycle-close"],
  },
  {
    id: "iterative-contract-review",
    title: "Ітеративний review contract",
    situation:
      "Згенерований план API migration має відповідати explicit compatibility rubric. Кожну версію можна перевіряти за однаковими критеріями.",
    patternId: "evaluator-optimizer",
    choices: [
      {
        id: "prompt-chaining",
        label: "Prompt chaining",
        feedback: "Fixed chain не використовує rubric, щоб покращувати слабкий candidate за результатами feedback.",
      },
      {
        id: "evaluator-optimizer",
        label: "Evaluator-optimizer",
        feedback: "Правильно. Stable evaluator може знаходити gaps і керувати обмеженими ітераціями.",
        correct: true,
      },
      {
        id: "routing",
        label: "Routing",
        feedback: "Задачу вже класифіковано; бракує iterative evaluation.",
      },
    ],
    correctMove: "Оцінюйте кожен candidate за compatibility rubric і зупиняйтеся, коли criteria виконані або подальшого progress немає.",
    consequence: "Ітерації спираються на evidence, а не на unbounded запит покращити відповідь.",
    relatedGates: ["validation", "lifecycle-close"],
  },
  {
    id: "open-ended-repo-investigation",
    title: "Open-ended repo investigation",
    situation:
      "Production-only failure не має відомого шляху. Agent має динамічно перевіряти logs і code, обирати tools, формувати hypotheses та зупинятися перед risky actions.",
    patternId: "agent",
    choices: [
      {
        id: "agent",
        label: "Agent",
        feedback: "Правильно. Шлях не визначений наперед, а наступний tool залежить від evidence попереднього кроку.",
        correct: true,
      },
      {
        id: "prompt-chaining",
        label: "Prompt chaining",
        feedback: "Fixed sequence буде крихкою, бо наступна діагностика залежить від ще невідомого evidence.",
      },
      {
        id: "orchestrator-worker",
        label: "Orchestrator-worker",
        feedback: "Декомпозиція може знадобитися пізніше, але стабільної task map для workers ще немає.",
      },
    ],
    correctMove: "Використайте bounded agent loop з explicit tool permissions, evidence checks і stop/escalation conditions.",
    consequence: "Динамічне дослідження дозволене без необмеженої authority на дії.",
    relatedGates: ["permission", "validation", "lifecycle-close"],
  },
] satisfies WorkflowClassifierCase[];

export const agenticLoopCases = [
  {
    id: "validation-loop",
    title: "Повторна failed validation",
    entryNodeId: "failed-validation",
    nodes: [
      {
        id: "failed-validation",
        title: "Loop не має нового evidence",
        situation: "Три local patches змінили сусідній code, але та сама validation command досі падає.",
        evidence: [
          "Текст failure не змінився у трьох runs.",
          "Diff виріс на 84 рядки.",
          "Жодна diagnostic не перевірила припущення про owner failing config.",
        ],
        choices: [
          {
            id: "run-targeted-diagnostic",
            action: "continue",
            label: "Запустити одну targeted diagnostic до наступного edit",
            feedback: "Таке продовження виправдане, бо воно створює новий evidence.",
            nextNodeId: "diagnostic-result",
          },
          {
            id: "repeat-local-patch",
            action: "continue",
            label: "Застосувати ще один local patch з тим самим припущенням",
            feedback: "Loop не може змістовно продовжуватися без нового evidence. Повторення plan потрібно зупинити.",
            outcome: "stopped",
          },
          {
            id: "zoom-out-now",
            action: "zoom-out",
            label: "Припинити edits і переоцінити ownership assumption",
            feedback: "Повторюваного сигналу вже достатньо для zoom out і перевірки higher layer.",
            outcome: "zoomed-out",
          },
        ],
      },
      {
        id: "diagnostic-result",
        title: "Diagnostic змінює task model",
        situation: "Targeted diagnostic простежує failing value до generated config, яким керує shared build script.",
        evidence: [
          "Відредагований local module не створює failing value.",
          "Shared build script заново генерує config під час кожного validation run.",
          "Зміна shared script виходить за ownership boundary поточної task.",
        ],
        choices: [
          {
            id: "fix-shared-with-authority",
            action: "continue",
            label: "Перепланувати навколо shared owner і продовжити лише з authority",
            feedback: "Наступна дія тепер спирається на новий evidence та explicit ownership check.",
            outcome: "complete",
          },
          {
            id: "ask-shared-owner",
            action: "ask-human",
            label: "Ескалувати shared-boundary рішення до owner",
            feedback: "Escalation доречна, коли evidence виявляє boundary поза поточною authority.",
            outcome: "escalated",
          },
          {
            id: "keep-local-plan",
            action: "continue",
            label: "Продовжити patch local module попри trace",
            feedback: "Це ігнорує новий source-of-truth evidence, тому продовження потрібно зупинити.",
            outcome: "stopped",
          },
        ],
      },
    ],
  },
  {
    id: "ui-evidence-loop",
    title: "Build passed, але UI evidence конфліктує",
    entryNodeId: "agent-report",
    nodes: [
      {
        id: "agent-report",
        title: "Validation і reported behavior не збігаються",
        situation: "Build passed, і agent повідомляє про success, але reviewer каже, що mobile action обрізано.",
        evidence: [
          "Lint і build пройшли успішно.",
          "Agent не надає screenshot або viewport observation.",
          "Reviewer повідомляє про visible mobile defect.",
        ],
        choices: [
          {
            id: "observe-mobile",
            action: "continue",
            label: "Перевірити affected mobile viewport перед рішенням",
            feedback: "Наступний крок шукає independent evidence для ризику, якого не покрили automated checks.",
            nextNodeId: "observed-mobile",
          },
          {
            id: "close-on-build",
            action: "stop",
            label: "Закрити task, бо automated validation пройшла",
            feedback: "Закриття task не підтримується evidence, бо reported UI risk не перевірено.",
            outcome: "stopped",
          },
          {
            id: "ask-acceptance",
            action: "ask-human",
            label: "Запитати reviewer про viewport і observed acceptance state",
            feedback: "Це доречно, коли report не містить достатніх деталей для відтворення.",
            outcome: "escalated",
          },
        ],
      },
      {
        id: "observed-mobile",
        title: "Independent observation підтверджує ризик",
        situation: "Перевірка narrow viewport показує, що primary action label обрізано fixed bottom navigation.",
        evidence: [
          "Defect відтворюється за ширини 360px.",
          "Automated suite не має layout assertion для цього state.",
          "Змінений CSS перебуває у scope поточної task.",
        ],
        choices: [
          {
            id: "targeted-ui-fix",
            action: "continue",
            label: "Зробити scoped fix, повторити UI QA і закрити з evidence",
            feedback: "Продовження обмежене observed evidence і відповідним UI QA gate.",
            outcome: "complete",
          },
          {
            id: "add-unit-only",
            action: "continue",
            label: "Додати unit test і пропустити повторне viewport observation",
            feedback: "Сам unit test не перевіряє visible behavior, у якому виявлено failure.",
            outcome: "stopped",
          },
          {
            id: "zoom-layout-system",
            action: "zoom-out",
            label: "Зробити zoom out, якщо fixed navigation виявляє shared layout flaw",
            feedback: "Це доречно, якщо local defect виявляє ширшу проблему ownership у shared layout.",
            outcome: "zoomed-out",
          },
        ],
      },
    ],
  },
] satisfies AgenticLoopCase[];

export const localLearningCases = [
  {
    id: "missed-ui-qa",
    title: "Поведінку UI пропущено після успішного build",
    situation: "Agent виправив visual component, запустив build і пропустив broken mobile layout.",
    failureSignal: "Validation passed, але видима поведінка була неправильною.",
    durableTargetId: "quality-gate",
    durableTarget: "UI QA gate",
    choices: [
      {
        id: "longer-prompt",
        label: "Зробити наступний prompt довшим",
        feedback: "Може допомогти в цій session, але не перехопить майбутні пропуски.",
      },
      {
        id: "ui-gate",
        label: "Додати UI QA gate для layout-affecting задач",
        feedback: "Правильно. Durable target відповідає режиму помилки.",
        correct: true,
      },
      {
        id: "docs",
        label: "Оновити docs для component usage",
        feedback: "Docs можуть допомогти, якщо usage був нечітким, але пропущена поведінка потребує QA gate.",
      },
    ],
    correctMove: "Запропонуйте UI QA gate для задач, що змінюють видимий layout або interaction.",
    consequence: "Майбутні задачі з більшою ймовірністю перевірять screen before close.",
    relatedGates: ["ui-qa", "durable-correction"],
  },
  {
    id: "repeated-import-error",
    title: "Повторна import-помилка",
    situation: "Той самий wrong import path спричинив два failed builds у схожих задачах.",
    failureSignal: "Повторна technical mistake, спіймана build.",
    durableTargetId: "validation-check",
    durableTarget: "Validation-перевірка",
    choices: [
      {
        id: "rule",
        label: "Додати broad rule, що забороняє нові imports",
        feedback: "Занадто широко. Це створює накладні витрати і блокує legitimate work.",
      },
      {
        id: "validation",
        label: "Додати або задокументувати targeted validation-перевірку",
        feedback: "Правильно. Помилка вимірювана і має перехоплюватися механічно.",
        correct: true,
      },
      {
        id: "memory",
        label: "Сказати agent, щоб запам'ятав це",
        feedback: "Це session-local, якщо correction не збережено в durable layer.",
      },
    ],
    correctMove: "Спрямуйте correction до targeted перевірки або test, а не до broad rule.",
    consequence: "Workflow ловить повторювані помилки без зайвих constraints.",
    relatedGates: ["validation", "durable-correction"],
  },
  {
    id: "repeated-boundary-violation",
    title: "Повторне порушення critical boundary",
    situation: "У різних tasks agent повторно намагається редагувати payment boundaries без перевірки approval policy repo.",
    failureSignal: "Стабільний repository invariant повторно пропускається до дії.",
    durableTargetId: "rule",
    durableTarget: "Rule",
    choices: [
      { id: "rule", label: "Додати narrow rule, що вимагає existing approval gate", feedback: "Правильно. Стабільний repo-wide invariant належить у scoped rule після approval.", correct: true },
      { id: "test", label: "Додати unit test для agent approval behavior", feedback: "Code test не може надійно забезпечити workflow authority decision." },
      { id: "prompt", label: "Згадати policy у наступному task prompt", feedback: "Це ремонтує лише current session і легко пропускається пізніше." },
    ],
    correctMove: "Запропонуйте narrow approved rule, що спрямовує critical-boundary edits через permission gate.",
    consequence: "У future tasks invariant спрацьовує до risky action.",
    relatedGates: ["permission", "durable-correction"],
  },
  {
    id: "repeatable-release-procedure",
    title: "Повторювана release procedure",
    situation: "Agents повторно пропускають steps у multi-command release verification procedure, придатній для кількох repositories.",
    failureSignal: "Reusable procedure виконується непослідовно.",
    durableTargetId: "skill",
    durableTarget: "Skill",
    choices: [
      { id: "docs", label: "Додати ще один narrative release paragraph", feedback: "Docs можуть пояснити policy, але failure стосується виконання reusable procedure." },
      { id: "skill", label: "Створити approved reusable release-verification skill", feedback: "Правильно. Bounded skill може об'єднати repeatable steps.", correct: true },
      { id: "rule", label: "Додати rule з усіма commands і branches", feedback: "Rule — невдалий container для substantial reusable procedure." },
    ],
    correctMove: "Спрямуйте approved reusable procedure до skill, а project-specific policy залиште в її authority layer.",
    consequence: "Procedure стає repeatable без перетворення rules на довгий runbook.",
    relatedGates: ["validation", "durable-correction"],
  },
  {
    id: "escaped-regression",
    title: "Пропущена behavior regression",
    situation: "Той самий parsing edge case ламався двічі, а expected behavior можна перевірити детерміновано.",
    failureSignal: "Повторювана code behavior регресує без executable coverage.",
    durableTargetId: "test",
    durableTarget: "Test",
    choices: [
      { id: "test", label: "Додати focused regression test для observed edge case", feedback: "Правильно. Цю behavior можна перевірити механічно й детерміновано.", correct: true },
      { id: "rule", label: "Додати rule бути уважними з parsing", feedback: "Така instruction менш точна й enforceable, ніж executable test." },
      { id: "ui-gate", label: "Вимагати manual UI QA для кожної parser change", feedback: "Цей failure стосується deterministic code behavior, а не visual acceptance." },
    ],
    correctMove: "Зафіксуйте пропущену behavior у focused regression test.",
    consequence: "Майбутні changes зупиняться на executable boundary, який раніше пропустив defect.",
    relatedGates: ["validation", "durable-correction"],
  },
  {
    id: "stale-setup-guidance",
    title: "Stale setup guidance",
    situation: "Двоє contributors запускають obsolete setup command, бо repository guide досі називає old script.",
    failureSignal: "Durable project guidance конфліктує з current repository interface.",
    durableTargetId: "docs-update",
    durableTarget: "Docs update",
    choices: [
      { id: "validation", label: "Додати validation check, що переписує command", feedback: "Check може виявити failure, але authoritative human-facing instruction лишається stale." },
      { id: "docs", label: "Оновити canonical setup docs після перевірки script", feedback: "Правильно. Сам source of truth потребує виправлення.", correct: true },
      { id: "prompt", label: "Сказати current agent, яку command використовувати", feedback: "Це виправляє лише current run і не захищає future readers." },
    ],
    correctMove: "Перевірте current script, а потім оновіть canonical setup documentation.",
    consequence: "Майбутні contributors отримують current project truth у місці використання.",
    relatedGates: ["source-of-truth", "durable-correction"],
  },
  {
    id: "stuck-loop-repeat",
    title: "Повторна stuck-loop behavior",
    situation: "У кількох tasks agent продовжує patch після повтору тієї самої validation failure без нового evidence.",
    failureSignal: "Продовження триває після evidence threshold для reassessment.",
    durableTargetId: "stop-condition",
    durableTarget: "Stop condition",
    choices: [
      { id: "longer-prompt", label: "Попросити більше persistence у наступному prompt", feedback: "Більша persistence підсилює failure mode замість його interception." },
      { id: "stop-condition", label: "Додати approved stop condition для repeated unchanged failure", feedback: "Правильно. Workflow має зупиняти continuation без нового evidence.", correct: true },
      { id: "docs", label: "Задокументувати кожен attempted patch", feedback: "History може допомогти з diagnosis, але не зупиняє repeated behavior." },
    ],
    correctMove: "Визначте stop/zoom-out threshold за repeated unchanged evidence і погодьте його для workflow.",
    consequence: "Майбутні loops зупинятимуться до symptom-fixing і growing diff.",
    relatedGates: ["validation", "lifecycle-close", "durable-correction"],
  },
  {
    id: "one-off-typo",
    title: "One-off typo виправлено",
    situation: "Agent один раз помиляється в local variable, compiler одразу це ловить, а correction проходить existing checks.",
    failureSignal: "Одиничний low-risk slip уже перехоплює existing mechanism.",
    durableTargetId: "none",
    durableTarget: "Без durable correction",
    choices: [
      { id: "rule", label: "Додати rule проти variable-name typos", feedback: "Це створює broad overhead для failure, який уже перехоплюється механічно." },
      { id: "none", label: "Лишити local fix і покластися на existing compiler check", feedback: "Правильно. Немає підтвердженого workflow gap, який потрібно виправляти." , correct: true },
      { id: "skill", label: "Створити naming skill для future tasks", feedback: "Нова procedure непропорційна одиничному typo, який уже перехоплено." },
    ],
    correctMove: "Закрийте з existing validation evidence; не створюйте durable artifact.",
    consequence: "Workflow не накопичує rules і tools для isolated slips.",
    relatedGates: ["validation", "durable-correction"],
  },
] satisfies LocalLearningCase[];

export const permissionRiskCases = [
  {
    id: "delete-file",
    title: "Видалення file",
    situation: "Agent хоче видалити файл, який вважає unused.",
    choices: [
      { id: "delete", label: "Погодити негайно", feedback: "Видалення може бути незворотним або зламати hidden references." },
      { id: "pause", label: "Пауза, пояснити ризик, перевірити references, ask approval", feedback: "Правильно. Це permission і ownership gate.", correct: true },
      { id: "rename", label: "Перейменувати без approval", feedback: "Перейменування теж змінює поведінку і потребує доказів." },
    ],
    correctMove: "Пауза, перевірити references, пояснити blast radius і ask approval перед видаленням.",
    consequence: "Workflow запобігає випадковій втраті даних або поведінки.",
    relatedGates: ["permission", "ownership", "validation"],
  },
  {
    id: "add-dependency",
    title: "Додавання dependency",
    situation: "Agent хоче встановити dependency, щоб розв'язати малу UI issue.",
    choices: [
      { id: "install", label: "Встановити, бо зручно", feedback: "Dependencies додають maintenance, security і bundle cost." },
      { id: "approval", label: "Ask approval і порівняти локальні alternatives", feedback: "Правильно. Dependency changes потребують permission і scope review.", correct: true },
      { id: "copy", label: "Скопіювати код із package вручну", feedback: "Це може створити licensing і maintenance problems." },
    ],
    correctMove: "Трактуйте додавання dependency як permission-gated і обгрунтуйте, чому локальний код недостатній.",
    consequence: "Project уникає casual scope і supply-chain growth.",
    relatedGates: ["permission", "validation"],
  },
  {
    id: "edit-agents",
    title: "Редагування AGENTS.md / CLAUDE.md",
    situation: "Agent хоче переписати project instruction files після однієї помилки.",
    choices: [
      { id: "rewrite", label: "Дозволити agent переписати файл", feedback: "Instruction layers є durable authority і потребують людського погодження." },
      { id: "propose", label: "Попросити малу proposed correction і погодити вручну", feedback: "Правильно. Durable instruction changes потребують approval.", correct: true },
      { id: "ignore", label: "Ігнорувати, бо помилка одна", feedback: "Можливо, але спершу класифікуйте, чи потрібна durable correction." },
    ],
    correctMove: "Вимагайте proposed durable correction і людське погодження перед редагуванням instruction files.",
    consequence: "Workflow уникає випадкового overconstraint і silent rule changes.",
    relatedGates: ["permission", "durable-correction"],
  },
  {
    id: "auth-boundary",
    title: "Зміна auth/API/payment boundary",
    situation: "Agent хоче змінити auth middleware, щоб unblock test.",
    choices: [
      { id: "quickfix", label: "Швидко patch boundary", feedback: "Critical boundaries потребують джерела, ownership, permission і validation gates." },
      { id: "escalate", label: "Stop, перевірити authority, ask approval, validate deeply", feedback: "Правильно. Це high-risk workflow territory.", correct: true },
      { id: "skip-tests", label: "Skip tests і rely on review", feedback: "Review допомагає, але validation обов'язкова для boundary changes." },
    ],
    correctMove: "Ескалюйте до high-risk lane і вимагайте approval перед зміною boundary.",
    consequence: "Workflow зменшує шанс security або payment regressions.",
    relatedGates: ["permission", "source-of-truth", "validation", "ownership"],
  },
  {
    id: "destructive-command",
    title: "Запуск destructive command",
    situation: "Agent пропонує command, що рекурсивно removes generated artifacts.",
    choices: [
      { id: "run", label: "Запустити, бо artifacts disposable", feedback: "Recursive destructive commands потребують path verification і approval." },
      { id: "verify", label: "Перевірити exact paths і ask approval", feedback: "Правильно. Permission gate зупиняє accidental destructive scope.", correct: true },
      { id: "manual", label: "Попросити agent вручну видалити similar files", feedback: "Manual deletion теж може бути destructive без explicit scope." },
    ],
    correctMove: "Перевірте resolved paths, поясніть ризик і ask approval перед destructive дією.",
    consequence: "Workflow уникає випадкового видалення поза intended workspace.",
    relatedGates: ["permission", "validation"],
  },
  {
    id: "continue-failed-validation",
    title: "Продовження після повторної failed validation",
    situation: "Та сама validation знову fails, а diff продовжує зростати.",
    choices: [
      { id: "continue", label: "Продовжити patching symptoms", feedback: "Це stuck-loop signal." },
      { id: "stop", label: "Stop і zoom out", feedback: "Правильно. Workflow має перервати повторну помилку.", correct: true },
      { id: "close", label: "Закрити з warning", feedback: "Lifecycle close потребує доказів, а не warning." },
    ],
    correctMove: "Stop loop, перевірте припущення і оберіть новий план або ask human.",
    consequence: "Workflow запобігає зростанню diff без доказів.",
    relatedGates: ["validation", "lifecycle-close"],
  },
  {
    id: "archive-before-close",
    title: "Архівування artifact перед lifecycle close",
    situation: "Agent хоче archive task artifacts до того, як acceptance стане чітким.",
    choices: [
      { id: "archive", label: "Archive immediately", feedback: "Artifacts можуть ще бути потрібні для review і доказів." },
      { id: "close-gate", label: "Спершу запустити lifecycle-close gate", feedback: "Правильно. Закриття лише після доказів і acceptance.", correct: true },
      { id: "delete", label: "Видалити artifacts для cleanup", feedback: "Це ризикованіше за archiving і теж потребує permission." },
    ],
    correctMove: "Тримайте artifacts, доки підтвердження закриття lifecycle не complete.",
    consequence: "Review trail лишається available, доки задачу не accepted.",
    relatedGates: ["lifecycle-close", "permission"],
  },
] satisfies DecisionScenario[];

export const practiceScenarios = [
  {
    id: "feature-local-to-shared",
    kind: "compact",
    title: "Feature-local helpers -> shared",
    situation: "Helper із двох рядків використовується одним feature. Agent пропонує перенести його в shared utilities, бо пізніше він може знадобитися іншому feature.",
    evidence: [
      "Поточний search знаходить одного caller усередині owning feature.",
      "Сусідні shared utilities мають кілька cross-feature consumers.",
      "Diff малий, але shared placement змінює long-term ownership.",
    ],
    choices: [
      { id: "move", label: "Перенести зараз і тримати API вузьким до другого caller", feedback: "Вузький API не замінює evidence, що shared ownership виправдане." },
      { id: "inspect", label: "Лишити local і перевірити usage та ownership conventions", feedback: "Правильно. Shared code потребує доказів ownership.", correct: true },
      { id: "duplicate", label: "Скопіювати в shared, але лишити local helper для compatibility", feedback: "Паралельні копії створюють ownership ambiguity без підтвердженого reuse." },
    ],
    correctMove: "Зупиніть перенесення, доки актуальне repo usage і ownership conventions не виправдають shared placement.",
    consequence: "Helper лишається local, доки shared ownership не підтверджено.",
    durableCorrectionCandidate: "Додати ownership gate note для local-to-shared movement.",
    relatedGates: ["ownership", "source-of-truth"],
  },
  {
    id: "docs-memory-conflict",
    kind: "full",
    title: "Docs vs Memory conflict",
    situation: "Memory і repository guide описують workflow A. Recent code та executable checks поводяться як workflow B, а guide не оновлювався місяцями.",
    choices: [
      { id: "memory", label: "Дотримуватися remembered workflow, доки maintainer його не замінить", feedback: "Memory є найменш durable evidence і не вирішує conflict." },
      { id: "docs", label: "Порівняти current code, checks, history і documented intent", feedback: "Правильно. Authority decision має врахувати stale docs і current executable evidence.", correct: true },
      { id: "ask-ai", label: "Запитати іншого agent, який опис виглядає стандартнішим", feedback: "Другий plausible continuation не є independent project evidence." },
    ],
    correctMove: "Перевірте intended migration за code, checks і change history, а потім узгодьте stale guide з цим repo evidence.",
    consequence: "Workflow розрізняє current behavior, intended policy і stale guidance замість універсальної переваги одного source.",
    durableCorrectionCandidate: "Оновити canonical docs після перевірки intent і, якщо практично, додати check для future drift.",
    relatedGates: ["source-of-truth", "validation", "lifecycle-close", "durable-correction"],
    assessment: {
      evidence: [
        "Repository guide називає workflow A і востаннє змінювався дев'ять місяців тому.",
        "Поточна implementation і два executable checks забезпечують workflow B.",
        "Git history показує, що workflow B введено навмисно, але guide не оновили.",
        "Memory повторює workflow A і не має source date.",
      ],
      dimensions: [
        {
          id: "authority-source",
          prompt: "Яке authority/source-of-truth рішення відповідає conflict?",
          memoryCue: "Authority залежить від типу питання, а freshness підтверджує repo evidence.",
          choiceOrder: ["docs-always-win", "triangulate-current-evidence", "ask-owner-first", "memory-until-approved"],
          choices: [
            {
              id: "triangulate-current-evidence",
              label: "Перевірити intent за current code, checks і change history",
              verdict: "aligned",
              explanation: "Це відділяє current behavior від intended policy і перевіряє stale-doc hypothesis за repo facts.",
              changesWhen: "Якщо owner із higher authority підтвердить, що old guide досі normative, implementation B стане defect.",
            },
            {
              id: "docs-always-win",
              label: "Дотримуватися repository guide, бо це durable source",
              verdict: "misaligned",
              explanation: "Durability не доводить freshness; observed conflict потребує перевірки, а не universal precedence rule.",
            },
            {
              id: "memory-until-approved",
              label: "Зберегти remembered workflow, доки його context не замінять",
              verdict: "unsafe",
              explanation: "Memory не має підтвердженої project authority і суперечить сильнішому current evidence.",
            },
            {
              id: "ask-owner-first",
              label: "Ескалувати до owner перед тлумаченням repo evidence",
              verdict: "misaligned",
              explanation: "Наданий history уже фіксує intentional migration, тому escalation до аналізу цього evidence лише затримує виправлення.",
              changesWhen: "Цей варіант стає доречним, якщо history неповний, суперечливий або не підтверджує approved intent.",
            },
          ],
        },
        {
          id: "workflow-audit",
          prompt: "Які workflow level та audit depth мають контролювати task?",
          memoryCue: "Спочатку розв'яжіть authority conflict, а вже потім обирайте edit sequence.",
          choiceOrder: ["prompt-chain-docs-fix", "evaluator-comparison", "route-conflict-deep-audit", "autonomous-agent-rewrite"],
          choices: [
            {
              id: "route-conflict-deep-audit",
              label: "Спрямувати authority conflict у workflow з audit relevant repo facts",
              verdict: "aligned",
              explanation: "Це не simple docs fix: conflicting authority потребує bounded synthesis evidence.",
            },
            {
              id: "prompt-chain-docs-fix",
              label: "Застосувати short prompt chain і переписати older guide за current code",
              verdict: "misaligned",
              explanation: "Наперед визначений rewrite припускає intended implementation до розв'язання authority conflict.",
            },
            {
              id: "evaluator-comparison",
              label: "Застосувати evaluator для порівняння описів з explicit repo acceptance criteria",
              verdict: "conditionally-valid",
              explanation: "Evaluator може підтримати audit, якщо criteria походять з authoritative source.",
              changesWhen: "Без authoritative criteria evaluation лише формалізує unresolved assumption.",
            },
            {
              id: "autonomous-agent-rewrite",
              label: "Дозволити agent динамічно узгодити code/docs і відзвітувати потім",
              verdict: "unsafe",
              explanation: "Динамічне exploration не дає authority непомітно обирати policy або переписувати durable guidance.",
            },
          ],
        },
        {
          id: "next-action",
          prompt: "Яка наступна orchestrator action?",
          memoryCue: "Продовжуйте лише після того, як evidence підтвердить intent або вкаже потрібну human authority.",
          choiceOrder: ["continue-from-memory", "zoom-out-verify-intent", "ask-human-with-evidence", "stop-permanently"],
          choices: [
            {
              id: "zoom-out-verify-intent",
              label: "Перевірити migration, а потім виправити stale layer",
              verdict: "aligned",
              explanation: "Наступна дія розв'язує authority conflict до зміни implementation або docs.",
            },
            {
              id: "continue-from-memory",
              label: "Продовжити з workflow A, бо Memory і prose docs погоджуються",
              verdict: "unsafe",
              explanation: "Узгодженість двох stale derivatives не переважає current repo evidence.",
            },
            {
              id: "stop-permanently",
              label: "Остаточно зупинити task, бо conflicting sources роблять change invalid",
              verdict: "misaligned",
              explanation: "Conflict потребує investigation або escalation, а не відмови без встановлення intent.",
            },
            {
              id: "ask-human-with-evidence",
              label: "Звернутися до відповідального фахівця з коротким summary conflict і repo evidence",
              verdict: "misaligned",
              explanation: "Поточний history уже підтверджує approved migration, тому наступна дія має узгодити stale guide, а не повторно відкривати вирішене питання intent.",
              changesWhen: "Escalation стає доречною, якщо repo evidence лишається неоднозначним або містить conflicting approvals.",
            },
          ],
        },
        {
          id: "durable-correction",
          prompt: "Яка durable correction виправдана після розв'язання conflict?",
          memoryCue: "Виправляйте stale durable layer без universal precedence rule.",
          choiceOrder: ["no-correction", "add-universal-rule", "update-canonical-docs", "validation-only"],
          choices: [
            {
              id: "update-canonical-docs",
              label: "Оновити canonical guide і додати drift check, якщо його можна перевірити",
              verdict: "aligned",
              explanation: "Durable source, що став stale, треба виправити; mechanical interception потрібне лише для relation, яку можна перевірити.",
            },
            {
              id: "add-universal-rule",
              label: "Додати rule, що current code завжди має перевагу над repository docs",
              verdict: "unsafe",
              explanation: "Universal precedence rule закріплює хибний принцип і може виправдати accidental implementation drift.",
            },
            {
              id: "no-correction",
              label: "Не робити durable change після цього conflict",
              verdict: "conditionally-valid",
              explanation: "Це обґрунтовано лише тоді, коли guide не canonical або його вже замінив authoritative mechanism.",
              changesWhen: "Якщо contributors досі використовують guide, stale state зберігає failure path.",
            },
            {
              id: "validation-only",
              label: "Додати лише executable check і не змінювати human-facing guide",
              verdict: "misaligned",
              explanation: "Check захищає behavior, але не виправляє canonical instruction для людей.",
            },
          ],
        },
      ],
      gatePrompt: "Які quality gates потрібні для цього authority conflict?",
      gateOptions: [
        { gateId: "source-of-truth", classification: "required", explanation: "Central risk полягає у виборі між conflicting authority claims." },
        { gateId: "validation", classification: "required", explanation: "Executable checks встановлюють current behavior і перевіряють alignment change." },
        { gateId: "ownership", classification: "useful", explanation: "Ownership важливий, якщо guide та implementation мають різних owners." },
        { gateId: "permission", classification: "insufficient", explanation: "Approval може бути потрібним для durable policy change, але permission сам по собі не встановлює, який source правильний." },
        { gateId: "ui-qa", classification: "unnecessary", explanation: "У наданому evidence немає visible behavior risk." },
        { gateId: "lifecycle-close", classification: "required", explanation: "Не можна закрити task, доки code і canonical guidance суперечать одне одному." },
        { gateId: "durable-correction", classification: "useful", explanation: "Використайте його для approval правильного target без broad precedence rule." },
      ],
      gateMemoryCue: "Обирайте gates за observed risk; approval gate сам по собі не встановлює project truth.",
      rationalePrompt: "Чому ваші authority, workflow, gate і next-action choices відповідають evidence?",
      rationaleDescription: "Назвіть source conflict, evidence, що змінює authority, та умову для продовження або escalation.",
      rationaleMemoryCue: "Корисне обґрунтування коротко пов'язує authority, evidence, gate і наступну дію.",
      calibratedRationale: "Memory не є project truth, а вік guide створює freshness conflict, а не automatic authority. Порівняйте code, executable checks і change history, щоб встановити current behavior та intended migration. Продовжуйте лише тоді, коли evidence підтверджує intent; інакше зверніться до responsible owner. Після approval виправте canonical stale layer і додайте mechanical drift check лише для relation, яку можна перевірити.",
      rationaleRubric: [
        "Названо authority layer і repo evidence для freshness.",
        "Пояснено, чому Memory або stale prose не отримують перевагу автоматично.",
        "Наступну дію пов'язано із source-of-truth або escalation gate.",
        "Durable correction спрямовано до stale layer без universal rule.",
      ],
      transferQuestion: "Який відсутній або conflicting repo evidence зробив би escalation кращою за оновлення guide?",
    },
  },
  {
    id: "validation-passes-ui-wrong",
    kind: "compact",
    title: "Validation passes, але UI wrong",
    situation: "Lint і build пройшли, agent повідомляє про completion, але independent mobile review показує cramped primary action.",
    evidence: [
      "Automated checks покривають syntax і build output, але не visible narrow-screen state.",
      "Reviewer відтворює issue за ширини 360px.",
    ],
    choices: [
      { id: "close", label: "Закрити з automated evidence і записати UI concern окремо", feedback: "Observed acceptance failure не можна відкласти й водночас закрити main risk без evidence." },
      { id: "uiqa", label: "Відкрити visible acceptance gate і перевірити affected viewport", feedback: "Правильно. Видима поведінка потребує власного gate.", correct: true },
      { id: "test", label: "Додати component test для action label перед close", feedback: "Test може допомогти пізніше, але не замінює observation layout state, у якому виявлено failure." },
    ],
    correctMove: "Використайте UI QA gate перед lifecycle close.",
    consequence: "Learner відділяє technical validation від visible quality.",
    durableCorrectionCandidate: "Додати UI QA до задач, що змінюють layout або interaction.",
    relatedGates: ["ui-qa", "lifecycle-close"],
  },
  {
    id: "symptom-fixing-growing-diff",
    kind: "compact",
    title: "Symptom-fixing із growing diff",
    situation: "Agent застосував чотири plausible local fixes. Failure лишається, diff зростає, а нового diagnostic evidence немає.",
    evidence: [
      "Сигнатура error не змінилася.",
      "Кожен patch припускає той самий local ownership layer.",
      "Жодний trace або source inspection не перевірив це assumption.",
    ],
    choices: [
      { id: "continue", label: "Дозволити ще один bounded patch, бо кожен diff малий", feedback: "Малі patches не створюють нового evidence; repeated unchanged signal означає stuck loop." },
      { id: "zoomout", label: "Зупинити edits і зробити zoom out для перевірки ownership assumption", feedback: "Правильно. Переоцініть plan і припущення.", correct: true },
      { id: "merge", label: "Зберегти partial diff, змінити validation command і продовжити", feedback: "Заміна check без пояснення persistent failure може приховати ризик." },
    ],
    correctMove: "Зупиніть loop, перевірте джерело помилки й оберіть новий plan.",
    consequence: "Diff перестає зростати без доказів.",
    durableCorrectionCandidate: "Додати stop condition після повторної failed validation.",
    relatedGates: ["validation", "lifecycle-close"],
  },
  {
    id: "edit-agents-file",
    kind: "compact",
    title: "Редагування AGENTS.md / CLAUDE.md",
    situation: "Після однієї помилки user просить agent безпосередньо змінити AGENTS.md, але repo rules вимагають approval для durable workflow changes.",
    evidence: [
      "User request дозволяє дослідити помилку.",
      "Repository instruction file є durable authority layer.",
      "Поточний rule вимагає proposed correction і human approval.",
    ],
    choices: [
      { id: "allow", label: "Застосувати user-requested edit і попросити review у summary", feedback: "Review після зміни не задовольняє repo requirement щодо попереднього approval." },
      { id: "proposal", label: "Підготувати smallest correction і отримати approval до edit", feedback: "Правильно. Durable layers потребують approval.", correct: true },
      { id: "ban", label: "Відхилити всі instruction-file changes, бо agents не змінюють authority", feedback: "Boundary полягає у controlled approval, а не в universal ban." },
    ],
    correctMove: "Попросіть minimal proposed durable correction і погодьте її вручну, якщо вона justified.",
    consequence: "Workflow поліпшується без silent self-modification.",
    durableCorrectionCandidate: "Додати durable correction gate для instruction-file edits.",
    relatedGates: ["permission", "durable-correction"],
  },
  {
    id: "longer-prompt-no-durable",
    kind: "compact",
    title: "Довший prompt без durable correction",
    situation: "Repeated workflow miss виправлено в current run через detailed prompt, але future interception layer не змінився.",
    evidence: [
      "Той самий class of miss стався у двох tasks.",
      "Longer prompt збережено лише в current chat.",
      "Durable target ще не обрано й не погоджено.",
    ],
    choices: [
      { id: "done", label: "Повторно використовувати longer prompt template у схожих sessions", feedback: "Reusable prompt може допомогти, але це ще не controlled interception layer." },
      { id: "classify", label: "Класифікувати recurrence і спрямувати justified durable correction", feedback: "Правильно. Вирішіть, чи виправдане майбутнє interception.", correct: true },
      { id: "rule", label: "Додати concise rule, бо miss стався більше одного разу", feedback: "Recurrence виправдовує classification, але не автоматично broadest target." },
    ],
    correctMove: "Вирішіть, чи correction належить до rule, skill, test, docs update, validation-перевірки, gate або stop condition.",
    consequence: "Learner відділяє session-local correction від durable improvement.",
    durableCorrectionCandidate: "Спрямуйте повторювані помилки до найменшого durable layer, який зможе перехопити їх у майбутньому.",
    relatedGates: ["durable-correction"],
  },
  {
    id: "adding-dependency",
    kind: "compact",
    title: "Додавання dependency",
    situation: "Agent може швидше реалізувати convenience helper з dependency, але package changes потребують approval, а repo має small local alternative.",
    evidence: [
      "Package додасть transitive maintenance і supply-chain surface.",
      "Local implementation трохи довший, але не змінює dependencies.",
      "Agent має edit authority, але не dependency-approval authority.",
    ],
    choices: [
      { id: "install", label: "Додати dependency в implementation branch і попросити approval пізніше", feedback: "Implementation first переносить permission gate після risky change." },
      { id: "gate", label: "Порівняти local option, пояснити tradeoff і попросити approval", feedback: "Правильно. Порівняйте local alternatives і зверніться по approval.", correct: true },
      { id: "copy", label: "Vendor потрібний helper code без зміни package manifest", feedback: "Vendoring може створити більший maintenance/licensing risk без вирішення authority." },
    ],
    correctMove: "Попросіть approval і обґрунтуйте, чому dependency потрібна.",
    consequence: "Workflow контролює maintenance і supply-chain risk.",
    durableCorrectionCandidate: "Додати dependency-change permission gate.",
    relatedGates: ["permission", "validation"],
  },
  {
    id: "auth-api-payment",
    kind: "full",
    title: "Зміна auth/API/payment boundary",
    situation: "User просить small payment-callback change. Agent може реалізувати її, але repo policy вимагає owner approval для boundary changes і окремої authority для merge/deploy.",
    choices: [
      { id: "patch", label: "Підготувати й merge narrow patch, бо так попросив user", feedback: "Task intent не надає автоматично boundary, merge або deploy authority." },
      { id: "highrisk", label: "Зібрати evidence, перейти в high-risk lane і попросити approval", feedback: "Правильно. Потрібні authority, approval і deep validation.", correct: true },
      { id: "skip", label: "Реалізувати локально й відкласти permission decision до deployment", feedback: "Implementation може перетнути protected boundary; відкладений gate не прибирає risk." },
    ],
    correctMove: "Зупиніть task і спрямуйте її через source-of-truth, ownership, permission та validation gates.",
    consequence: "Workflow захищає critical product boundaries.",
    durableCorrectionCandidate: "Додати або уточнити high-risk lane лише якщо existing workflow не перехопив boundary change.",
    relatedGates: ["permission", "source-of-truth", "ownership", "validation", "lifecycle-close", "durable-correction"],
    assessment: {
      evidence: [
        "User дозволяє працювати над task, але не надає merge/deploy authority.",
        "Repository instructions вимагають approval від payment-boundary owner до implementation changes.",
        "Failing test покриває happy-path callback, але не replay, signature або rollback behavior.",
        "Запропонований diff має шість рядків і змінює callback acceptance condition.",
      ],
      dimensions: [
        {
          id: "authority-source",
          prompt: "Яке authority/source-of-truth рішення контролює boundary?",
          memoryCue: "Task intent, implementation truth і merge/deploy authority є окремими рішеннями.",
          choiceOrder: ["tests-define-authority", "owner-only-source", "separate-authorities", "user-authorizes-all"],
          choices: [
            {
              id: "separate-authorities",
              label: "Розділити task intent, boundary approval і behavioral evidence",
              verdict: "aligned",
              explanation: "Рішення розділяє intent, implementation truth і approval authority.",
            },
            {
              id: "user-authorizes-all",
              label: "Вважати user request authority для implementation, merge і deploy narrow change",
              verdict: "unsafe",
              explanation: "Запит task не скасовує explicit repo permission та release boundaries.",
            },
            {
              id: "tests-define-authority",
              label: "Вважати passing callback test authority для behavior і release approval",
              verdict: "unsafe",
              explanation: "Tests надають behavioral evidence, але не ownership, merge або deploy permission.",
            },
            {
              id: "owner-only-source",
              label: "Попросити boundary owner визначити всі implementation details до repo inspection",
              verdict: "misaligned",
              explanation: "Approval від owner важливий, але orchestrator спершу може зібрати non-destructive repo evidence.",
            },
          ],
        },
        {
          id: "workflow-audit",
          prompt: "Які workflow level та audit depth відповідають payment change із шести рядків?",
          memoryCue: "Audit depth залежить від business/security risk, а не від розміру diff.",
          choiceOrder: ["small-diff-chain", "high-risk-routed-audit", "bounded-agent-investigation", "evaluator-only"],
          choices: [
            {
              id: "high-risk-routed-audit",
              label: "Застосувати high-risk lane з ownership та independent validation",
              verdict: "aligned",
              explanation: "Audit depth залежить від business/security blast radius, а не від розміру diff.",
            },
            {
              id: "small-diff-chain",
              label: "Застосувати short prompt chain, бо code diff і affected function малі",
              verdict: "unsafe",
              explanation: "Lightweight fixed path пропускає risk classification і permission boundary.",
            },
            {
              id: "evaluator-only",
              label: "Застосовувати evaluator-optimizer, доки existing callback test не пройде",
              verdict: "misaligned",
              explanation: "Incomplete tests не встановлюють missing authority і не покривають abuse cases.",
            },
            {
              id: "bounded-agent-investigation",
              label: "Дозволити bounded agent investigation, але зупинитися до protected edits і звернутися до owner",
              verdict: "conditionally-valid",
              explanation: "Read-only investigation може бути корисним за explicit tool permissions і чіткої edit boundary.",
              changesWhen: "Якщо repo path і required evidence уже відомі, routed deterministic workflow буде простішим.",
            },
          ],
        },
        {
          id: "next-action",
          prompt: "Яка наступна orchestrator action?",
          memoryCue: "Зупиніться на permission boundary і зверніться по рішення з concrete evidence-backed plan.",
          choiceOrder: ["zoom-out-boundary", "continue-unmerged", "stop-all-work", "ask-human-with-plan"],
          choices: [
            {
              id: "ask-human-with-plan",
              label: "Зупинитися з evidence-backed plan і звернутися до authorized owner",
              verdict: "aligned",
              explanation: "Ця action зберігає momentum і переносить protected decision до correct authority layer.",
            },
            {
              id: "continue-unmerged",
              label: "Продовжити local implementation без merge або deploy",
              verdict: "unsafe",
              explanation: "Надана policy вимагає approval до implementation, тому навіть reversible local edit перетинає explicit permission boundary.",
              changesWhen: "Цей варіант стає прийнятним лише тоді, коли policy прямо дозволяє isolated local implementation до owner approval.",
            },
            {
              id: "stop-all-work",
              label: "Зупинити все investigation, доки owner не напише exact patch",
              verdict: "misaligned",
              explanation: "Non-destructive збір evidence може поліпшити approval request.",
            },
            {
              id: "zoom-out-boundary",
              label: "Зробити zoom out і визначити callback ownership та failure modes до request",
              verdict: "conditionally-valid",
              explanation: "Це доречно, якщо current evidence не визначає protected contract або owner.",
              changesWhen: "Коли ownership і risks уже відомі, подальший zoom out лише затримує рішення.",
            },
          ],
        },
        {
          id: "durable-correction",
          prompt: "Яка durable correction потрібна після цієї task?",
          memoryCue: "Створюйте durable correction лише тоді, коли evidence показує interception gap.",
          choiceOrder: ["refine-high-risk-gate", "not-warranted-yet", "new-rule-always", "add-happy-path-test"],
          choices: [
            {
              id: "not-warranted-yet",
              label: "Не додавати нічого без evidence, що current gate пропустив risk",
              verdict: "aligned",
              explanation: "Сама risky task не доводить workflow gap; спершу перевірте, чи policy перехопила risk.",
            },
            {
              id: "new-rule-always",
              label: "Додавати new payment rule після кожної boundary task для більшої обережності",
              verdict: "unsafe",
              explanation: "Overlapping rules створюють overhead і приховують actual authority policy.",
            },
            {
              id: "refine-high-risk-gate",
              label: "Уточнити high-risk gate, якщо trigger пропустив callback-condition changes",
              verdict: "conditionally-valid",
              explanation: "Це доречний target, коли post-task evidence підтверджує interception gap.",
              changesWhen: "Зміна не потрібна, якщо current gate уже вимагав pause та approval.",
            },
            {
              id: "add-happy-path-test",
              label: "Додати ще один happy-path test як єдину durable correction",
              verdict: "misaligned",
              explanation: "Narrow test не покриває permission, replay, signature або rollback risks.",
            },
          ],
        },
      ],
      gatePrompt: "Які quality gates потрібні перед close цієї change?",
      gateOptions: [
        { gateId: "source-of-truth", classification: "required", explanation: "Payment contract і existing policy треба встановити до change." },
        { gateId: "ownership", classification: "required", explanation: "Protected boundary має explicit owner і approval path." },
        { gateId: "permission", classification: "required", explanation: "Implementation, merge і deploy authority не можна виводити з task intent." },
        { gateId: "validation", classification: "required", explanation: "Validation має покривати callback і failure modes, а не лише happy path." },
        { gateId: "ui-qa", classification: "unnecessary", explanation: "Надана change не має visible UI behavior." },
        { gateId: "lifecycle-close", classification: "required", explanation: "Close потребує approval evidence і risk-matched validation." },
        { gateId: "durable-correction", classification: "useful", explanation: "Застосовуйте лише після перевірки, чи workflow не зміг перехопити risk." },
      ],
      gateMemoryCue: "Навіть малий diff може вимагати deep gates, якщо boundary має великий blast radius.",
      rationalePrompt: "Чому authority, audit, gate і next-action choices відповідають high-risk task?",
      rationaleDescription: "Відділіть implementation evidence від permission authority і поясніть, чому small diff не зменшує audit depth.",
      rationaleMemoryCue: "Назвіть, хто має authority, якого evidence бракує і який gate контролює наступну дію.",
      calibratedRationale: "User request встановлює task intent, а repository policy і boundary owner визначають, чи можна починати implementation; merge/deploy лишаються окремими authorities. Diff із шести рядків змінює payment acceptance condition, тому task належить до high-risk lane із source, ownership, permission, validation і lifecycle-close gates. Зберіть non-destructive evidence, а потім зверніться до authorized owner з concrete plan. Додавайте durable correction лише тоді, коли existing gate не спрацював або виявився нечітким.",
      rationaleRubric: [
        "Розділено task intent, implementation truth і merge/deploy authority.",
        "Audit depth пояснено через business/security risk, а не розмір diff.",
        "Наступну action пов'язано з permission і validation evidence.",
        "Durable rule не створено без evidence про workflow gap.",
      ],
      transferQuestion: "Яка explicit policy в іншому repo зробила б reversible local implementation прийнятною до owner approval?",
    },
  },
] satisfies PracticeScenario[];
