import type { ChapterNavItem, LearningChapter } from "../schemas";

const totalChapters = 14;

export const learningChapters = [
  {
    id: "ai-under-the-hood",
    slug: "ai-under-the-hood",
    order: 1,
    totalChapters,
    label: "01",
    status: "available",
    title: "AI under the hood",
    eyebrow: "Foundation",
    summary:
      "Практична ментальна модель: чому контекст, факти repo, source of truth, validation і gates важливі для AI coding роботи.",
    practices: [
      "Помічати, коли відповідь є лише plausible continuation.",
      "Називати authority layer для repo-specific твердження.",
      "Обирати перший validation move перед тим, як agent продовжить.",
    ],
    sections: [
      {
        id: "plausible-continuation",
        eyebrow: "Core model",
        title: "Plausible не означає project-true",
        summary: "LLM output може виглядати логічно, але бути неправдивим для конкретного repo.",
        paragraphs: [
          "LLM може завершити plausible pattern, який виглядає логічно, але не є правдою для цього repo, доки його не заземлено у фактах repo.",
          "Orchestrator визначає тип питання, обирає правильний authority layer, перевіряє релевантний source of truth і підбирає validation або quality gate.",
        ],
      },
      {
        id: "context-grounding",
        eyebrow: "Контекст",
        title: "Контекст корисний лише тоді, коли заземлює задачу",
        summary: "Більше тексту prompt не автоматично означає кращий контекст.",
        paragraphs: [
          "Корисний контекст містить шляхи файлів, актуальні patterns, project docs, тести, constraints і критерії прийняття.",
          "Коли твердження впливає на конкретну задачу repo, наступний крок - перевірити факт repo або запустити validation, яка може це довести.",
        ],
      },
    ],
    checkpoint: {
      id: "repo-pattern-check",
      prompt:
        "Agent каже, що helper треба перенести в src/lib, бо це common practice у Next.js apps. Він не шукав докази в цьому repo.",
      instruction: "Визначте authority layer, source of truth і чи agent може продовжувати.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Authority layer: факти repo і ownership boundaries, а не generic convention.",
        "Source of truth: поточна структура файлів, nearby feature patterns, existing shared utilities і project docs.",
        "Наступна дія: зупинити крок, перевірити repo і продовжувати тільки якщо докази підтримують shared ownership.",
      ],
      durableHabit:
        "Коли рекомендація спирається на common practice, але змінює ownership, спершу вимагайте докази repo.",
      relatedConcepts: ["authority layer", "source of truth", "ownership gate"],
    },
    sourceRefs: [],
    interactive: "self-check",
  },
  {
    id: "context-engineering",
    slug: "context-engineering",
    order: 2,
    totalChapters,
    label: "02",
    status: "available",
    title: "Context engineering",
    eyebrow: "Grounding",
    summary:
      "Context engineering означає вибір доказів, які потрібні agent для поточної задачі, а не набивання prompt.",
    practices: [
      "Відділяти корисні докази від зайвої довжини prompt.",
      "Називати відсутній контекст до того, як agent почне діяти.",
      "Обирати, що треба перевірити, а не вгадувати.",
    ],
    sections: [
      {
        id: "context-is-evidence",
        eyebrow: "Evidence",
        title: "Добрий контекст звужує невизначеність",
        summary: "Контекст має зменшувати gap між generic pattern і actual repo state.",
        paragraphs: [
          "Корисний контекст відповідає на питання: які файли важливі, яка очікувана поведінка, які constraints і що вважається завершенням.",
          "Поганий контекст може бути довгим, але незаземленим: broad instructions, повторювані попередження або нагадування без authority.",
        ],
      },
      {
        id: "context-before-action",
        eyebrow: "Workflow habit",
        title: "Спитайте, що треба знати перед редагуванням",
        summary: "Orchestrator має знайти відсутні факти до того, як loop витратить редагування.",
        paragraphs: [
          "Якщо agent не може назвати релевантні файли, тести, docs або критерії прийняття, він ще не готовий змінювати код.",
          "Практичний крок малий: перевірити відсутнє джерело, потім продовжити з вужчою задачею.",
        ],
      },
    ],
    checkpoint: {
      id: "context-check",
      prompt:
          "Prompt став довшим після bug, але agent досі не inspected failing file або test.",
      instruction: "Вирішіть, це кращий контекст чи просто більше слів.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Це недостатній grounding.",
        "Попросіть релевантний файл, вивід помилки і критерії прийняття перед наступним редагуванням.",
        "Якщо помилка повторюється, розгляньте durable correction замість довшого prompt.",
      ],
      durableHabit: "Надавайте перевагу контексту, підкріпленому джерелами, над повторюваним текстом інструкцій.",
      relatedConcepts: ["контекст", "source of truth", "durable correction"],
    },
    sourceRefs: [],
    interactive: "self-check",
  },
  {
    id: "authority-source-of-truth",
    slug: "authority-source-of-truth",
    order: 3,
    totalChapters,
    label: "03",
    status: "available",
    title: "Authority / source of truth",
    eyebrow: "Authority",
    summary: "Authority-рішення перетворюють vague trust questions на конкретні validation кроки.",
    practices: [
      "Класифікувати тип питання.",
      "Обирати authority layer.",
      "Перевіряти за релевантним source of truth.",
    ],
    sections: [
      {
        id: "authority-layer",
        eyebrow: "Decision model",
        title: "Спершу оберіть authority layer",
        summary: "Правильне джерело залежить від типу питання.",
        paragraphs: [
          "Поведінка repo має бути заземлена в коді, тестах, поведінці під час запуску і project docs.",
          "Поведінка інструмента або framework має бути заземлена в актуальних official docs. Продуктовий напрям спирається на погоджені рішення або людське погодження.",
        ],
      },
      {
        id: "conflict-resolution",
        eyebrow: "Conflict",
        title: "Вирішуйте конфлікти процедурно",
        summary: "Не просіть модель арбітрувати між конфліктними джерелами.",
        paragraphs: [
          "Якщо Memory, docs, код і результат моделі конфліктують, оберіть layer з правильною authority для цього питання.",
          "Результат - validation крок: перевірити джерело, запустити перевірку, ask approval або stop.",
        ],
      },
    ],
    checkpoint: {
      id: "authority-checkpoint",
      prompt: "Memory каже, що один package standard. Current imports показують інший package.",
      instruction: "Оберіть authority layer і наступну дію.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Authority layer: актуальні факти repo і durable project docs.",
        "Наступна дія: перевірити imports і docs, потім заземлити рішення там.",
        "Не просіть model вгадувати, яка memory newer.",
      ],
      durableHabit: "Коли джерела конфліктують, класифікуйте authority замість обговорення довіри.",
      relatedConcepts: ["authority layer", "source-of-truth gate"],
    },
    sourceRefs: [],
    interactive: "authority-matrix",
  },
  {
    id: "workflow-vs-agent",
    slug: "workflow-vs-agent",
    order: 4,
    totalChapters,
    label: "04",
    status: "available",
    title: "Workflow vs agent",
    eyebrow: "Control model",
    summary: "Workflow - це заздалегідь визначений шлях. Agent - це динамічний loop з інструментами в межах.",
    practices: [
      "Вирішувати, коли фіксований шлях достатній.",
      "Вирішувати, коли обмежене дослідження корисне.",
      "Ставити loop limits до початку agentic work.",
    ],
    sections: [
      {
        id: "workflow",
        eyebrow: "Workflow",
        title: "Використовуйте workflows, коли шлях відомий",
        summary: "Відома послідовність не має ставати free-running agent loop.",
        paragraphs: [
          "Для задач огляд -> редагування -> validation -> підсумок workflow дає передбачуваність і малий overhead.",
          "Orchestrator все ще ставить gates, але шлях не потребує динамічного дослідження.",
        ],
        sourceRefs: ["anthropic-building-effective-agents"],
      },
      {
        id: "agent",
        eyebrow: "Agent",
        title: "Використовуйте agents, коли шлях треба відкрити",
        summary: "Agentic loops корисні, коли наступний крок залежить від результатів інструментів.",
        paragraphs: [
          "Agent спостерігає, планує, діє, перевіряє і вирішує, чи продовжувати в межах.",
          "Orchestrator має визначити stop conditions, ризикові дії і validation gates до того, як autonomy зросте.",
        ],
        sourceRefs: ["willison-agent-definition"],
      },
    ],
    checkpoint: {
      id: "workflow-agent-check",
      prompt:
        "Typo fix має known file і known validation command. Agent пропонує broad repo exploration loop.",
      instruction: "Оберіть workflow або agent.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Використайте simple workflow, а не broad agent loop.",
        "Шлях відомий і низькоризиковий.",
        "Поставте targeted validation і підтвердження закриття lifecycle як gate.",
      ],
      durableHabit: "Не додавайте agentic autonomy, коли small workflow достатній.",
      relatedConcepts: ["workflow", "agent", "validation gate"],
    },
    sourceRefs: ["anthropic-building-effective-agents", "willison-agent-definition"],
    interactive: "self-check",
  },
  {
    id: "core-workflow-patterns",
    slug: "core-workflow-patterns",
    order: 5,
    totalChapters,
    label: "05",
    status: "available",
    title: "Core workflow patterns",
    eyebrow: "Decision vocabulary",
    summary: "Six workflow patterns дають словник orchestrator для вибору рівня контролю.",
    practices: [
      "Розпізнавати six workflow patterns.",
      "Обирати pattern за формою задачі.",
      "Приєднувати правильний ризик і gate до кожного pattern.",
    ],
    sections: [
      {
        id: "patterns-as-vocabulary",
        eyebrow: "Vocabulary",
        title: "Patterns не є framework-вимогами",
        summary: "Використовуйте patterns, щоб міркувати про контроль, а не нав'язувати runtime.",
        paragraphs: [
          "Prompt chaining, routing, parallelization, orchestrator-worker, evaluator-optimizer і agent - це словник рішень.",
          "MVP не встановлює LangGraph і не implements workflow runtime. Він навчає, коли pattern підходить для coding-agent задачі.",
        ],
        sourceRefs: ["anthropic-building-effective-agents", "langgraph-workflows-agents"],
      },
    ],
    checkpoint: {
      id: "pattern-checkpoint",
      prompt: "Малу відому послідовність трактують як широку автономну задачу.",
      instruction: "Класифікуйте кращий pattern і ризик.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Використайте prompt chaining для known sequence.",
        "Уникайте зайвого agentic scope.",
        "Додайте validation gate і підтвердження закриття lifecycle.",
      ],
      durableHabit: "Оберіть найменший workflow pattern, який дає достатній контроль.",
      relatedConcepts: ["prompt chaining", "workflow level", "validation gate"],
    },
    sourceRefs: ["anthropic-building-effective-agents", "langgraph-workflows-agents"],
    interactive: "workflow-classifier",
  },
  {
    id: "coding-agent-workflow",
    slug: "coding-agent-workflow",
    order: 6,
    totalChapters,
    label: "06",
    status: "available",
    title: "Coding agent workflow",
    eyebrow: "Repo lifecycle",
    summary: "Coding-agent orchestration накладає workflow patterns на рішення життєвого циклу repo-задач.",
    practices: [
      "Заземлювати твердження у файлах repo і project docs.",
      "Тримати приклади поведінки vendor локальними й підкріпленими актуальними docs.",
      "Закривати задачі з доказами, а не впевненістю.",
    ],
    sections: [
      {
        id: "repo-files-win",
        eyebrow: "Repo truth",
        title: "Файли repo перемагають для поведінки repo",
        summary: "Поточний repository є authority для того, як працює цей repository.",
        paragraphs: [
          "Project docs, нотатки задачі, AGENTS.md, CLAUDE.md, тести й актуальний код можуть бути authority layers залежно від питання.",
          "Приклади vendor можуть ілюструвати workflow, але вони не універсальні правила для кожного coding-agent продукту.",
        ],
      },
      {
        id: "evidence-close",
        eyebrow: "Lifecycle",
        title: "Закривайте з доказами",
        summary: "Кінець coding-agent задачі - це контрольна точка доказів.",
        paragraphs: [
          "Корисний close-out називає змінені файли, запуск validation, залишкові ризики і потрібне людське погодження.",
          "Якщо бракує доказів, наступна дія orchestrator: продовжити, stop, zoom out або ask human, а не закрити.",
        ],
      },
    ],
    checkpoint: {
      id: "coding-workflow-check",
      prompt: "Agent стверджує project convention, але посилається лише на приклад vendor.",
      instruction: "Оберіть source of truth і наступну дію.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Використовуйте приклади vendor лише як приклади.",
        "Для поведінки repo перевіряйте файли repo і docs.",
        "Продовжуйте лише після того, як convention заземлено в цьому проєкті.",
      ],
      durableHabit: "Тримайте продуктові приклади окремо від фактів repo.",
      relatedConcepts: ["repo facts", "source-of-truth gate"],
    },
    sourceRefs: ["openai-codex-docs", "claude-code-docs"],
    interactive: "self-check",
  },
  {
    id: "task-lanes-audit-depth",
    slug: "task-lanes-audit-depth",
    order: 7,
    totalChapters,
    label: "07",
    status: "available",
    title: "Task lanes / audit depth",
    eyebrow: "Risk lanes",
    summary: "Audit depth має відповідати blast radius задачі.",
    practices: [
      "Класифікувати задачі як low, medium або high risk.",
      "Обирати глибину аудиту перед редагуваннями agent.",
      "Ескалювати до погодження, коли ризик перетинає межі.",
    ],
    sections: [
      {
        id: "lanes",
        eyebrow: "Lanes",
        title: "Low, medium, high",
        summary: "Risk lanes тримають малі задачі легкими, а ризикові задачі контрольованими.",
        paragraphs: [
          "Low-risk задачі можуть використовувати легкий потік огляд/редагування/validation. Medium-risk задачі потребують перевірок ownership. High-risk задачі потребують approval, source-of-truth gates і глибшої validation.",
          "Ризик походить від blast radius, незворотності, security, shared ownership, dependency changes і нечіткого прийняття.",
        ],
      },
    ],
    checkpoint: {
      id: "audit-depth-check",
      prompt: "Agent хоче змінити shared auth code, щоб виправити один failing test.",
      instruction: "Оберіть lane і gates.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Це high risk.",
        "Використайте source-of-truth, ownership, permission, validation і lifecycle-close gates.",
        "Попросіть людське погодження перед зміною boundary.",
      ],
      durableHabit: "Не дозволяйте local symptom сховати high-risk boundary.",
      relatedConcepts: ["audit depth", "permission gate", "ownership gate"],
    },
    sourceRefs: [],
    interactive: "permission-risk",
  },
  {
    id: "agentic-loop",
    slug: "agentic-loop",
    order: 8,
    totalChapters,
    label: "08",
    status: "available",
    title: "Agentic loop",
    eyebrow: "Loop control",
    summary: "Orchestrator контролює, коли agent loop продовжує, зупиняється або робить zoom out.",
    practices: [
      "Називати кроки observe / plan / act / перевірка.",
      "Визначати stop conditions до того, як loop розширюється.",
      "Розпізнавати повторювані сигнали помилки.",
    ],
    sections: [
      {
        id: "loop-shape",
        eyebrow: "Loop",
        title: "Observe -> plan -> act -> перевірка",
        summary: "Agentic loop потребує критеріїв виходу, а не просто руху.",
        paragraphs: [
          "Loop спостерігає докази, планує обмежену наступну дію, діє, перевіряє результат, потім виходить, продовжує, asks human або робить zoom out.",
          "Повторна failed validation, growing diffs, нечітка authority або ризикові дії є stop signals.",
        ],
        sourceRefs: ["anthropic-building-effective-agents"],
      },
    ],
    checkpoint: {
      id: "loop-checkpoint",
      prompt: "Agent уже спробував три patches, але та сама помилка залишається.",
      instruction: "Оберіть continue, stop, zoom out або ask human.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Зупиніть продовження того самого loop.",
        "Зробіть zoom out і перевірте джерело помилки або припущення.",
        "Ask human, якщо source of truth або product intent нечіткі.",
      ],
      durableHabit: "Повторна failed validation є stop signal, а не запрошенням продовжувати patching.",
      relatedConcepts: ["agentic loop", "stop condition", "zoom out"],
    },
    sourceRefs: ["anthropic-building-effective-agents"],
    interactive: "agentic-loop",
  },
  {
    id: "local-learning",
    slug: "local-learning",
    order: 9,
    totalChapters,
    label: "09",
    status: "available",
    title: "Local learning",
    eyebrow: "Durable correction",
    summary: "Local learning означає контрольоване workflow improvement, а не навчання моделі чи silent self-modification.",
    practices: [
      "Відділяти session-local correction від durable improvement.",
      "Класифікувати сигнал помилки.",
      "Спрямовувати durable correction до правильної цілі.",
    ],
    sections: [
      {
        id: "durable-model",
        eyebrow: "Model",
        title: "Сигнал помилки -> durable interception",
        summary: "Корисна durable correction допомагає раніше ловити схожі помилки в майбутніх задачах.",
        paragraphs: [
          "Модель: сигнал помилки -> класифікувати помилку -> запропонувати durable correction -> погодження orchestrator -> оновити durable layer -> майбутнє перехоплення.",
          "Agent може запропонувати correction. Orchestrator погоджує, чи це належить до правила, skill, тесту, docs update, validation-перевірки, quality gate або stop condition.",
        ],
      },
      {
        id: "not-autonomous",
        eyebrow: "Boundary",
        title: "Не autonomous self-improvement",
        summary: "Local learning не змінює ваги моделі і не переписує rules мовчки.",
        paragraphs: [
          "Session-local fix допомагає лише поточному запуску. Durable workflow improvement зберігається там, де майбутній запуск може його зачепити.",
          "Durable target має перехопити помилку без зайвого overhead або scope creep.",
        ],
      },
    ],
    checkpoint: {
      id: "local-learning-check",
      prompt:
        "Agent каже, що наступного разу не пропустить UI check, але rule, test, docs, gate або validation-перевірка не змінюються.",
      instruction: "Класифікуйте correction.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Це session-local correction.",
        "Якщо пропуск імовірно повториться, запропонуйте durable target.",
        "Для пропущеної видимої поведінки UI QA gate може підходити краще, ніж rule.",
      ],
      durableHabit: "Спрямуйте correction до найменшого durable layer, який перехопить майбутню помилку.",
      relatedConcepts: ["session-local", "durable workflow improvement"],
    },
    sourceRefs: [],
    interactive: "local-learning",
  },
  {
    id: "quality-gates",
    slug: "quality-gates",
    order: 10,
    totalChapters,
    label: "10",
    status: "available",
    title: "Quality gates",
    eyebrow: "Control surface",
    summary: "Gates є інструментами рішень, що ловлять ризик рано без перетворення workflow на bureaucracy.",
    practices: [
      "Обирати правильний gate для ризику.",
      "Використовувати evals як легкі durable verification assets.",
      "Ставити на паузу ризикові дії до того, як вони створять шкоду.",
    ],
    sections: [
      {
        id: "gate-set",
        eyebrow: "Gate set",
        title: "Seven MVP gates",
        summary:
          "Validation, source-of-truth, ownership, permission, UI QA, lifecycle-close і durable correction gates покривають практичну поверхню контролю.",
        paragraphs: [
          "Gates не є paperwork. Це малі точки рішень, що ловлять неправильну authority, ризикові дії, пропущену видиму поведінку і передчасне закриття.",
          "Evals можна викладати легко як durable verification assets: regression test із повторної coding mistake або перевірка результату/поведінки UI.",
        ],
        sourceRefs: ["anthropic-agent-evals"],
      },
    ],
    checkpoint: {
      id: "gate-check",
      prompt: "Build passes, але змінений UI ще не переглянуто, а agent хоче закрити задачу.",
      instruction: "Оберіть відсутні gates.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Validation gate пройдено.",
        "UI QA gate досі відсутній.",
        "Lifecycle-close gate не може пройти без доказів видимої поведінки.",
      ],
      durableHabit: "Використовуйте gate, що відповідає ризику; успіх build не є універсальним прийняттям.",
      relatedConcepts: ["validation gate", "UI QA gate", "lifecycle-close gate"],
    },
    sourceRefs: ["anthropic-agent-evals"],
    interactive: "permission-risk",
  },
  {
    id: "zoom-out",
    slug: "zoom-out",
    order: 11,
    totalChapters,
    label: "11",
    status: "available",
    title: "Zoom-out",
    eyebrow: "Reassessment",
    summary: "Zoom-out thinking перериває повторювані локальні fixes, коли справжня проблема - план, припущення або authority layer.",
    practices: [
      "Розпізнавати symptom-fixing.",
      "Зупиняти growing diffs без доказів.",
      "Переоцінювати authority, план і scope.",
    ],
    sections: [
      {
        id: "zoom-signals",
        eyebrow: "Signals",
        title: "Коли zoom out",
        summary: "Повторювані локальні fixes можуть ховати неправильну модель задачі.",
        paragraphs: [
          "Zoom out, коли validation продовжує падати, diffs зростають, agent змінює стратегію без доказів або source of truth лишається нечітким.",
          "Наступна дія може бути stop, перевірити вищий authority layer, ask human або запропонувати durable stop condition.",
        ],
      },
    ],
    checkpoint: {
      id: "zoom-check",
      prompt: "Diff подвоївся, а початкова помилка не змінилася.",
      instruction: "Оберіть наступну дію orchestrator.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Зупиніть локальний patch loop.",
        "Zoom out до моделі помилки і authority layer.",
        "Не закривайте і не продовжуйте без нових доказів.",
      ],
      durableHabit: "Growing diff плюс незмінена помилка є zoom-out signal.",
      relatedConcepts: ["zoom out", "stop condition", "validation gate"],
    },
    sourceRefs: [],
    interactive: "agentic-loop",
  },
  {
    id: "practice-scenarios",
    slug: "practice-scenarios",
    order: 12,
    totalChapters,
    label: "12",
    status: "available",
    title: "Практичні сценарії",
    eyebrow: "Capstone",
    summary: "Guided mixed scenarios показують, як authority, workflow, audit depth, gates і durable correction працюють разом перед direct assessment.",
    practices: [
      "Декомпозувати mixed situation до вибору orchestrator move.",
      "Використовувати immediate feedback, щоб пов'язати choice з consequence.",
      "Підготуватися до тих самих рішень без scaffolding у direct practice.",
    ],
    sections: [
      {
        id: "capstone",
        eyebrow: "Practice",
        title: "Накопичувальна практика",
        summary: "Цей chapter є guided bridge до assessment mode.",
        paragraphs: [
          "Кожен сценарій має форму: ситуація -> варіанти -> наслідок -> правильний крок orchestrator -> кандидат на durable correction.",
          "Використовуйте immediate feedback, щоб відпрацювати ownership, source of truth, UI QA, zoom-out, workflow authority, durable correction, permission gates і high-risk boundaries. Route для direct practice приховує feedback до submit.",
        ],
      },
    ],
    checkpoint: {
      id: "practice-check",
      prompt: "У цьому змішаному сценарії є ризикова дія, нечіткий source of truth і повторна помилка.",
      instruction: "Назвіть перший крок.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Зробіть паузу і класифікуйте ризик перед дією.",
        "Оберіть authority і gates.",
        "Продовжуйте лише після того, як наступний крок має докази.",
      ],
      durableHabit: "Змішані сценарії варто розкладати на authority, workflow, gate і рішення щодо дій.",
      relatedConcepts: ["practice", "orchestrator judgment"],
    },
    sourceRefs: [],
    interactive: "practice-scenarios",
  },
  {
    id: "operating-checklist",
    slug: "operating-checklist",
    order: 13,
    totalChapters,
    label: "13",
    status: "available",
    title: "Operating checklist",
    eyebrow: "Checklist",
    summary: "Стислий контрольний список перетворює learning path на operating habit для AI coding задач.",
    practices: [
      "Запускайте контрольний список до і після роботи agent.",
      "Використовуйте його, щоб пояснювати рішення orchestrator.",
      "Закривайте лише з доказами.",
    ],
    sections: [
      {
        id: "checklist",
        eyebrow: "Operating loop",
        title: "Before, during, after",
        summary: "Малого контрольного списку достатньо, якщо він веде до правильних рішень.",
        paragraphs: [
          "Before: класифікуйте ризик задачі, оберіть authority layer, workflow-рівень, визначте gates і stop conditions.",
          "During: перевіряйте докази, тримайте scope вузьким, переривайте stuck loops, ask approval для ризикових дій.",
          "After: запустіть validation, перевірте видиму поведінку, якщо релевантно, підсумуйте докази і вирішіть, чи потрібна durable correction.",
        ],
      },
    ],
    checkpoint: {
      id: "checklist-check",
      prompt: "Agent готовий закрити після редагувань, але доказів прийняття не наведено.",
      instruction: "Оберіть помилку контрольного списку.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Бракує доказів lifecycle-close.",
        "Попросіть результат validation і докази прийняття.",
        "Розгляньте UI QA або durable correction, якщо задача містила ці ризики.",
      ],
      durableHabit: "Не закривайте без доказів.",
      relatedConcepts: ["operating checklist", "lifecycle-close gate"],
    },
    sourceRefs: [],
    interactive: "self-check",
  },
  {
    id: "references",
    slug: "references",
    order: 14,
    totalChapters,
    label: "14",
    status: "available",
    title: "References / advanced reading",
    eyebrow: "Grounding",
    summary: "References є дослідницькими anchors для validation, підкріпленої джерелами, а не доказом для продуктових рішень.",
    practices: [
      "Відділяти продуктові рішення від зовнішніх фактичних тверджень.",
      "Використовуйте актуальні official docs для поведінки продукту.",
      "Тримайте advanced reading поза MVP core path.",
    ],
    sections: [
      {
        id: "reference-role",
        eyebrow: "Reference role",
        title: "Джерела для зовнішніх тверджень",
        summary: "Короткі відсилки до джерел допомагають швидко побачити, на чому ґрунтуються ключові зовнішні фактичні твердження, без перевантаження читача.",
        paragraphs: [
          "Calibration artifact визначає продуктові рішення для цього site. Зовнішні твердження про agents, workflow patterns, HITL, evals, інструменти і permissions потребують дослідницького проходу, підкріпленого джерелами.",
          "Поведінка vendor/product швидко змінюється, тому твердження про конкретні coding-agent інструменти треба перевіряти за актуальними official docs.",
        ],
      },
    ],
    checkpoint: {
      id: "reference-check",
      prompt: "Draft каже, що всі coding agents request approval перед редагуванням rules.",
      instruction: "Вирішіть, чи це можна сформулювати як є.",
      revealTitle: "Очікуваний orchestrator move",
      reveal: [
        "Ні. Це твердження про конкретний продукт із зовнішнього джерела.",
        "Або пом'якшіть твердження, або перевірте за актуальними official docs для кожного інструмента.",
        "Не перетворюйте поведінку одного vendor на універсальне правило.",
      ],
      durableHabit: "Актуальні official docs є authority для поточної поведінки продукту.",
      relatedConcepts: ["твердження з джерелами", "current docs"],
    },
    sourceRefs: [
      "anthropic-building-effective-agents",
      "openai-practical-agents",
      "langgraph-workflows-agents",
      "langchain-human-in-loop",
      "openai-codex-docs",
      "claude-code-docs",
    ],
    interactive: "self-check",
  },
] satisfies LearningChapter[];

export const learningPath = learningChapters.map(
  ({ id, slug, title, label, status }) => ({ id, slug, title, label, status }),
) satisfies ChapterNavItem[];

export const availableChapters = learningChapters;

export const firstAvailableChapter = learningChapters[0];
