import type { UiDictionary } from "../schemas";

export const ui = {
  metadata: {
    defaultTitle: "AI Orchestrator Guide",
    titleTemplate: "%s | AI Orchestrator Guide",
    description:
      "Практичний навчальний сайт для developer-orchestrators: AI workflow orchestration, source of truth, quality gates і судження в agentic loop.",
    siteName: "AI Orchestrator Guide",
  },
  layout: {
    brandTitle: "Orchestrator Learning",
    brandSubtitle: "Практика workflow judgment",
    chapterNavigation: "Навігація розділами",
    mobileQuickNavigation: "Швидка мобільна навігація",
    overview: "Огляд",
    languageLabel: "Мова",
    switchLanguage: "Змінити мову",
    closeChapterPicker: "Закрити вибір розділу",
    closeChapters: "Закрити розділи",
  },
  navigation: {
    chapters: "Розділи",
    continue: "Продовжити",
    practice: "Практика",
    refs: "Джерела",
    previous: "Назад",
    next: "Далі",
    current: "Поточний",
    planned: "Заплановано",
    chapterMap: "Мапа розділів",
    practiceScenarios: "Практичні сценарії",
  },
  home: {
    mobileContext: "Огляд",
    eyebrow: "Практичний навчальний продукт",
    title: "AI workflow orchestration для developer judgment",
    summary:
      "Навчіться обирати authority layer, workflow-рівень, глибину аудиту, quality gates і наступну дію orchestrator для AI coding задач.",
    progressLabel: "Прогрес поточного розділу",
    chapterPath: (count) => `${count} розділів у шляху`,
    startPrompt: "Почніть з першого доступного розділу",
    howToEyebrow: "Як користуватися",
    howToTitle: "Почніть сфокусовано, потім розширюйте контекст",
    howToBody:
      "Огляд тримає навчальний шлях компактним. Відкрийте розділ, прочитайте пояснення, зробіть контрольне рішення і спробуйте легкий практичний інструмент для цієї навички.",
    startLearning: "Почати навчання",
    practice: "Практика",
    references: "Джерела",
    mapEyebrow: "MVP шлях",
    mapTitle: "Мапа розділів",
    mapBody:
      "Кожен пункт відкриває розділ із навчальним текстом, контрольним рішенням і практикою для однієї навички orchestrator.",
  },
  chapter: {
    mobileContext: (order) => `Розділ ${order}`,
    progressLabel: "Прогрес поточного розділу",
    progressText: (order, total) => `Розділ ${order} / ${total}`,
    practiceTargetEyebrow: "Ціль практики",
    practiceTargetTitle: "Що тренує цей розділ",
    patternSetEyebrow: "Набір patterns",
    patternSetTitle: "Шість workflow patterns",
    gateSetEyebrow: "Набір gates",
    gateSetTitle: "Сім quality gates",
    useWhen: "Коли використовувати",
    avoidWhen: "Коли не використовувати",
    risk: "Ризик",
    example: "Приклад",
    watchOut: "На що звернути увагу",
    sourceNotesEyebrow: "Нотатки джерел",
    sourceNotesTitle: "Опорні дослідницькі anchors для цього фрагмента",
    sourceNotesBody:
      "Це легкі anchors для майбутньої validation, підкріпленої джерелами. Вони прив'язані до зовнішніх фактичних тверджень, а не до продуктових рішень.",
    adjacentLabel: "Сусідні розділи",
  },
  practice: {
    mobileContext: "Практика",
    eyebrow: "Практичні сценарії",
    title: "Практичні сценарії",
    summary:
      "Використайте 8 MVP сценаріїв, щоб тренувати змішане судження orchestrator: authority, workflow-рівень, глибину аудиту, gates і durable correction.",
    progressLabel: "Статус маршруту",
    scenarioCount: "8 сценаріїв",
    capstone: "Підсумкова практика",
    howToEyebrow: "Як користуватися",
    howToTitle: "Завершіть рішення до review",
    howToBody:
      "Це assessment workspace. Шість сценаріїв перевіряють compact mixed decision; два full capstones вимагають визначити authority, workflow, gates, наступну дію, durable correction і self-reviewed rationale до final feedback.",
  },
  references: {
    mobileContext: "Джерела",
    eyebrow: "Джерела / advanced reading",
    title: "Джерела та advanced reading",
    summary:
      "Перевірені source anchors, maintenance metadata й optional advanced reading для зовнішніх тверджень про agents, workflows, інструменти, HITL, evals і permissions.",
    progressLabel: "Статус маршруту",
    backlog: "Source lifecycle",
    validateLater: "Перевірено 2026-07-11",
    sourcePolicyEyebrow: "Політика джерел",
    sourcePolicyTitle: "Використовуйте джерела для зовнішніх тверджень",
    sourcePolicyBody:
      "Продуктові рішення походять із calibration artifact. Зовнішні фактичні твердження використовують точні primary sources. Vendor behavior лишається scoped до названого продукту й потребує refresh за актуальними official docs.",
    operationalEyebrow: "Operational index",
    operationalTitle: "Знайдіть потрібний control",
    operationalBody:
      "Використовуйте ці links під час live task. Вони ведуть до canonical chapter content, а не дублюють framework тут.",
    actionsTitle: "Дії / stop decisions",
    actionsBody:
      "Вирішіть, чи agent має continue, stop, ask for help або zoom out.",
    loopDecisionsLink: "Рішення agentic loop",
    zoomOutLink: "Zoom-out signals",
    gatesTitle: "Quality gates",
    gatesBody: "Перейдіть прямо до gate, що відповідає поточному ризику.",
    patternsTitle: "Workflow patterns",
    patternsBody: "Відкрийте canonical pattern entry для форми задачі, яку класифікуєте.",
    checklistTitle: "Operating checklist",
    checklistBody: "Запустіть before / during / after checklist для активної coding-agent задачі.",
    checklistLink: "Відкрити operating checklist",
    practiceTitle: "Practice modes",
    practiceBody:
      "Chapter 12 є guided learning bridge. Route Practice є direct scenario workspace.",
    guidedPracticeLink: "Guided practice chapter",
    directPracticeLink: "Direct practice workspace",
    sourceLifecycle: {
      scopeLabel: "Scope",
      verifiedLabel: "Перевірено",
      volatilityLabel: "Volatility",
      vendorScopeLabel: "Source scope",
      volatilityLabels: {
        stable: "Stable concept",
        "vendor-specific": "Vendor-specific",
        heuristic: "Heuristic",
      },
    },
    groups: [
      {
        category: "core",
        eyebrow: "Ключові джерела",
        title: "Workflow і agent concepts",
        description:
          "Primary anchors для workflow patterns, agent loops, HITL і evals.",
      },
      {
        category: "vendor-docs",
        eyebrow: "Vendor docs",
        title: "Поточна поведінка продуктів",
        description:
          "Точні official docs для scoped product behavior. Refresh ці твердження зі змінами vendor behavior.",
      },
      {
        category: "advanced",
        eyebrow: "Advanced reading",
        title: "Концепти наступного рівня",
        description:
          "Тримайте це як optional reading. Воно не має ставати MVP blueprint.",
      },
    ],
  },
  learning: {
    decisionCheckpoint: "Контрольне рішення",
    checkpointTitle: "Зробіть authority-рішення",
    hideExpectedMove: "Сховати очікуваний крок",
    revealExpectedMove: "Показати очікуваний крок",
    durableHabit: "Стійка звичка:",
    relatedConcepts: "Пов'язані concepts",
    sourceAnchors: "Опорні джерела",
    sourceListLabel: "Опорні джерела для цього розділу",
  },
  interactives: {
    eyebrow: "Interactive",
    scenariosLabel: "сценарії",
    choiceInstruction: "Оберіть крок orchestrator для цього сценарію.",
    correctMove: "Правильний крок:",
    consequence: "Наслідок:",
    relatedGates: "Пов'язані gates",
    chooseHint: "Оберіть крок, щоб побачити відгук.",
    selfCheckTitle: "Self-check / reveal cards",
    selfCheckIntro:
      "Використайте ці швидкі перевірки, щоб розрізняти правдоподібні відповіді, докази і durable workflow improvement.",
    authorityMatrixTitle: "Source-of-Truth Authority Matrix",
    authorityMatrixIntro:
      "Спершу оберіть authority layer, а вже потім вирішуйте, чи може agent продовжувати.",
    authorityLayer: "Authority layer",
    sourceOfTruth: "Source of truth",
    workflowClassifierTitle: "Workflow Classifier",
    workflowClassifierIntro:
      "Класифікуйте workflow pattern і помітьте ризик orchestrator до початку роботи.",
    targetPattern: "Цільовий pattern",
    risk: "Ризик",
    agenticLoopTitle: "Agentic Loop Simulator",
    agenticLoopIntro:
      "Тренуйте рішення: loop має продовжитися, зупинитися, перейти до zoom out або звернутися до людини.",
    localLearningTitle: "Local Learning Loop Wizard",
    localLearningIntro:
      "Класифікуйте сигнал помилки і спрямуйте correction до найменшого durable layer, який перехопить схожу помилку пізніше.",
    failureSignal: "Сигнал помилки",
    durableTarget: "Durable target",
    permissionRiskTitle: "Permission / Risk Gate Stress-Test",
    permissionRiskIntro:
      "Зробіть паузу, поясніть ризик, визначте gate, а потім вирішіть: попросити approval, виконати validation, зупинитися або перейти до zoom out.",
    practiceScenariosTitle: "Практичні сценарії",
    practiceScenariosIntro:
      "Змішані сценарії поєднують ownership, source of truth, UI QA, zoom-out, durable correction, permission gates і high-risk boundaries.",
    durableCorrectionCandidate: "Кандидат на durable correction",
    guidedMode: "Guided practice",
    guidedModeIntro:
      "Використовуйте негайний feedback, щоб навчитися розкладати змішану ситуацію на authority, evidence, gates, дію та durable correction.",
    assessmentMode: "Assessment workspace",
    assessmentModeIntro:
      "Завершіть structured decisions до перегляду calibrated response. У full capstones feedback щодо правильності з'являється лише після final submit.",
    evidence: "Доступні докази",
    beginAssessment: "Почати assessment",
    step: "Крок",
    of: "з",
    back: "Назад",
    nextStep: "Наступний крок",
    submitDecision: "Підтвердити рішення",
    submitAssessment: "Завершити full assessment",
    checkDecision: "Перевірити рішення",
    continueAfterReview: "Продовжити після review",
    viewGuidedSummary: "Переглянути guided summary",
    reset: "Скинути",
    retry: "Повторити сценарій",
    requiredChoice: "Оберіть один варіант, перш ніж продовжити.",
    requiredGates: "Оберіть щонайменше один quality gate, перш ніж продовжити.",
    requiredRationale: "Додайте коротке обґрунтування перед submit.",
    reviewTitle: "Огляд за кожним виміром",
    reviewIntro:
      "Structured decisions перевіряються детерміновано. Письмове обґрунтування оцінюєте ви самі, а не машина.",
    guidedReviewIntro:
      "Перегляньте повну послідовність рішень, яку ви відпрацювали, а потім застосуйте framework до нового контексту через transfer question.",
    decisionTrace: "Послідовність рішень",
    traceLabels: {
      "authority-source": "Authority / source",
      "workflow-audit": "Workflow / audit",
      gates: "Quality gates",
      "next-action": "Наступна дія",
      "durable-correction": "Durable correction",
      rationale: "Self-review обґрунтування",
    },
    detailedReview: "Детальний review",
    transferQuestion: "Transfer question",
    memoryCue: "Опорна теза",
    evidenceWouldChange: "Evidence, який змінив би це рішення",
    selfReviewed: "Self-reviewed",
    selectedAnswer: "Ваше рішення",
    calibratedRationale: "Calibrated rationale",
    rationaleSelfReview: "Self-review обґрунтування",
    rationaleNotGraded:
      "Формулювання не отримує бал. Порівняйте його з rubric і calibrated rationale.",
    missingCriticalGates: "Пропущені critical gates",
    gateSelected: "Обрано",
    gateNotSelected: "Не обрано",
    reviewStates: {
      aligned: "Узгоджено",
      "conditionally-reasonable": "Умовно обґрунтовано",
      "needs-review": "Потребує перегляду",
    },
    gateClassifications: {
      required: "Обов'язковий",
      useful: "Корисний за відповідних умов",
      unnecessary: "Зайвий для цих доказів",
      insufficient: "Недостатній сам по собі",
    },
    loopStage: "Етап рішення",
    loopFeedback: "Feedback щодо рішення",
    loopContinue: "Перейти до нових доказів",
    loopOutcome: "Результат loop",
    loopOutcomes: {
      complete: "Завершено з доказами",
      stopped: "Зупинено",
      "zoomed-out": "Виконано zoom out",
      escalated: "Ескаловано до людини",
    },
  },
} satisfies UiDictionary;
